/** @typedef {{ metaDescription: string; intro: string; quickTips: [string,string,string,string]; strategy: string[] }} Locale */
/** @param {string} categoryId @param {string} difficulty @param {Locale} en @param {Locale} tr @param {Locale} de @returns {object} */
function g(categoryId, difficulty, en, tr, de) {
  return { categoryId, difficulty, content: { en, tr, de } };
}

/** @type {Record<string, object>} */
export const cooperativeExpert = {
  pandemic: g("cooperative-games", "simple",
    { metaDescription: "Expert Pandemic: outbreak cascade prevention, role action sequencing, and cure-before-eradication tempo.", intro: "Expert Pandemic is outbreak graph management. One chain reaction loses the game; winners sequence roles to cap cube growth before pursuing cures.", quickTips: ["Treat outbreaks as the real loss condition, not cube supply.", "Scientist cures with 4 cards; always feed them matching colors.", "Operations Expert builds research stations before anyone travels.", "Cure all four before eradicating any color."], strategy: ["Outbreak cascade math: each outbreak adds 3-8 cubes in chain; cap at 6 total outbreaks by midgame through proactive cube removal, not reactive firefighting.", "Role action sequencing: Medic clears 2+ cubes per action in hotspot; Researcher feeds Scientist; Dispatcher enables Medic double-moves.", "Cure tempo: cure at 5-6 outbreaks, not 3—curing doesn't reduce board pressure; cube removal does.", "Infection deck forecasting: when 3+ epidemic cards remain, hold 2 cards of each color before drawing—epidemic spikes kill unprepared tables.", "Endgame eradication trap: eradicating one color before all four cures wastes actions—complete all cures first, then eradicate in one sweep."] },
    { metaDescription: "Uzman Pandemic: salgin zinciri onleme ve rol aksiyon sirasi.", intro: "Uzman Pandemic salgin graf yonetimidir. Tek zincir reaksiyon oyunu kaybettirir.", quickTips: ["Kayip kosulu salgin sayisidir.", "Bilim insana 4 kartla tedavi verin.", "Operasyon uzmani once istasyon kurar.", "Sonce dort tedavi, sonra yok etme."], strategy: ["Salgin zinciri matematigi.", "Medic hotspot temizler.", "5-6 salginda tedavi.", "Epidemi oncesi 2 kart tut.", "Dort tedavi sonra yok etme."] },
    { metaDescription: "Pandemic-Expertenstrategie: Outbreak-Kaskaden und Rollen-Sequencing.", intro: "Experten-Pandemic ist Outbreak-Graph-Management.", quickTips: ["Outbreaks sind Loss Condition.", "Scientist mit 4 Karten fuettern.", "Ops Expert baut Stationen.", "Alle 4 Cures vor Eradication."], strategy: ["Outbreak-Cascade-Math.", "Medic 2+ Cubes pro Action.", "Cure bei 5-6 Outbreaks.", "2 Karten pro Farbe vor Epidemic.", "Alle Cures vor Eradication."] }
  ),

  "forbidden-island": g("cooperative-games", "simple",
    { metaDescription: "Expert Forbidden Island: flood rate management, shore-up priority lanes, and treasure runner specialization.", intro: "Forbidden Island is tempo against rising water. Experts shore up treasure tile lanes before collecting and specialize one runner per treasure.", quickTips: ["Shore up treasure tiles before they flood, not after.", "Navigator moves two players—use for treasure runs.", "Diver can swim through flooded tiles—shortcuts critical paths.", "Don't collect treasure until all 4 tiles are shored up."], strategy: ["Flood rate management: at water level 4+, shore up 2 tiles per turn minimum—collection pauses until flood rate stabilizes.", "Shore-up priority: treasure tiles first, then corners and edges (sink first), then paths between treasures.", "Runner specialization: assign one player per treasure color; Navigator shuttles them to collection points.", "Pilot burst timing: save Pilot fly for emergency shore-up when 3+ treasure tiles flood simultaneously.", "Helicopter escape: move all players to Fool's Landing 2 turns before deck empty—waiting 1 turn risks sink."] },
    { metaDescription: "Uzman Forbidden Island: sel hizi yonetimi ve hazinenin korunmasi.", intro: "Forbidden Island yukselen suya karsi tempodur.", quickTips: ["Hazine karolarini batmadan guclendirin.", "Navigator iki oyuncu tasir.", "Diver selden yuzerek gecer.", "4 karo guclenmeden hazine almayin."], strategy: ["Su 4+ iken gunde 2 guclendirme.", "Hazine karolari oncelikli.", "Renk basina bir kosucu.", "Pilot acil guclendirme icin.", "2 tur once helikopter cikisi."] },
    { metaDescription: "Forbidden-Island-Expertenstrategie: Flood-Rate-Management.", intro: "Forbidden Island ist Tempo gegen steigendes Wasser.", quickTips: ["Treasure-Tiles vor Flood shoren.", "Navigator bewegt zwei.", "Diver schwimmt durch Flood.", "4 Tiles shoren vor Sammlung."], strategy: ["2 Shore-Ups/Tag bei Level 4+.", "Treasure-Tiles zuerst.", "Ein Runner pro Farbe.", "Pilot-Burst fuer Notfall.", "Heli 2 Runden vor Ende."] }
  ),

  "forbidden-desert": g("cooperative-games", "simple",
    { metaDescription: "Expert Forbidden Desert: sand clearing lanes, water conservation, and solar deck timing.", intro: "Forbidden Desert adds sand and thirst. Experts clear sand lanes to buried parts and conserve water through role synergies.", quickTips: ["Clear sand from launch pad tiles before digging for parts.", "Water carrier refills at oasis—never let team drop below 3 water.", "Solar deck: sun beats move sand; storm beats dig.", "Meteorologist reduces storm intensity—use before big digs."], strategy: ["Sand lane clearing: clear 3-tile path to each part location before digging—digging without lane wastes actions on re-burial.", "Water conservation: never move without purpose when below 5 water; Explorer's diagonal move saves 1 water per turn.", "Solar deck timing: plan digs on sun turns; use Meteorologist to skip storm before multi-tile dig.", "Part collection order: collect parts nearest launch pad first—reduces carry distance on final assembly.", "Jet pack + Tunnel: combine for 3-tile sand clear in one turn when part is 2 sand deep."] },
    { metaDescription: "Uzman Forbidden Desert: kum temizleme ve su tasarrufu.", intro: "Forbidden Desert kum ve susuzluk ekler.", quickTips: ["Firlatma padlerinden kumu temizleyin.", "Su tasiyici vahada doldurur.", "Gunes kaz, firtina kazma.", "Meteorolog firtinayi azaltir."], strategy: ["Kazmadan 3 karoluk yol ac.", "5 su altinda gereksiz hareket yok.", "Gunes turunda kaz.", "Yakin parcalari once topla.", "Jet pack+tunel combo."] },
    { metaDescription: "Forbidden-Desert-Expertenstrategie: Sand-Lanes und Wasser.", intro: "Forbidden Desert ergaenzt Sand und Durst.", quickTips: ["Sand von Launch-Pad-Tiles.", "Water Carrier an Oase.", "Sonne graben, Sturm nicht.", "Meteorologist vor Dig."], strategy: ["3-Tile-Lane vor Dig.", "Keine Moves unter 5 Wasser.", "Digs an Sonnentagen.", "Naechste Parts zuerst.", "Jetpack+Tunnel-Combo."] }
  ),

  "spirit-island": g("cooperative-games", "complicated",
    { metaDescription: "Expert Spirit Island: slow/growth curves, fear generation sequencing, and presence placement for control thresholds.", intro: "Spirit Island experts manage slow/growth power curves across rounds. Fear generation and presence placement determine when you flip from defensive to dominant.", quickTips: ["Turn 1-3: growth and presence only; minimal energy spending.", "Fear cards trigger at thresholds—plan 2 fear/turn minimum from round 4.", "Presence tracks control; 2+ presence on a land enables many powers.", "Blight cascade prevention beats explorer removal every time."], strategy: ["Slow/growth curve: rounds 1-2 pure growth; round 3 first energy power; round 4+ fear generation. Breaking this curve leaves you energy-starved when invaders spike.", "Fear sequencing: generate 2 fear/turn from round 4 to hit first fear card by round 6—fear cards remove invaders without spending actions.", "Presence placement: 2 presence on high-value lands (coasts, wetlands) enables reclaim and push; 1 presence everywhere wastes threshold bonuses.", "Blight cascade math: one blight on a land with 3+ invaders cascades to 2 adjacent—remove explorers before adding blight, always.", "Innate power timing: trigger innate on round 5-6 when presence thresholds hit; innate before growth on those rounds.", "Spirit pairing: Lightning + River synergize fear+energy; Bringer of Dreams pairs with any fear spirit for threshold acceleration."] },
    { metaDescription: "Uzman Spirit Island: slow/growth egrisi ve korku uretim sirasi.", intro: "Spirit Island uzmanlari slow/growth guc egrisini yonetir. Korku ve varlik yerlesimi kontrol esiklerini belirler.", quickTips: ["1-3. tur: buyume ve varlik; az enerji.", "4. turdan 2 korku/tur hedefle.", "2+ varlik cogu gucu acar.", "Leke zinciri oncelikli."], strategy: ["1-2 tur saf buyume.", "4. turdan korku uretimi.", "Degerli arazide 2 varlik.", "Leke zinciri matematigi.", "5-6. turda dogal guc.", "Lightning+River sinerjisi."] },
    { metaDescription: "Spirit-Island-Expertenstrategie: Slow/Growth-Kurven.", intro: "Spirit-Island-Experten managen Slow/Growth-Power-Kurven.", quickTips: ["R1-3: Growth+Presence.", "Ab R4: 2 Fear/Turn.", "2+ Presence fuer Powers.", "Blight-Cascade verhindern."], strategy: ["R1-2 pure Growth.", "Fear ab R4.", "2 Presence auf High-Value.", "Blight-Cascade-Math.", "Innate R5-6.", "Lightning+River-Synergie."] }
  ),

  gloomhaven: g("cooperative-games", "complicated",
    { metaDescription: "Expert Gloomhaven: initiative manipulation, loss card economy, and element infusion sequencing.", intro: "Gloomhaven experts treat loss cards as a finite resource and sequence initiative to control monster activation order. Element infusion timing unlocks power card bonuses.", quickTips: ["Never lose more than 1 card per scenario on trash attacks.", "Go late initiative to act after monsters move into position.", "Infuse elements the round BEFORE you need the bonus.", "Loss card retirement: lose 2 cards max per long rest cycle."], strategy: ["Loss card economy: each scenario has a loss budget (~6-8 cards); track per room. Trash attacks that cost 2 loss cards are scenario-loss conditions.", "Initiative manipulation: late initiative (80+) lets monsters move into your AoE; early initiative (20-) for kill-before-activation on fragile targets.", "Element infusion sequencing: infuse fire/ice round N for power card bonus round N+1—infusing same round wastes the element.", "Long rest timing: long rest when 3+ loss cards played and health below 50%; short rest for stamina recovery only.", "Class synergies: Spellweaver summons + Cragheart obstacles = zero-loss monster control.", "Scenario retirement: lose scenario rather than lose 4+ cards—card economy matters more than single scenario win."] },
    { metaDescription: "Uzman Gloomhaven: inisiyatif manipulasyonu ve kayip kart ekonomisi.", intro: "Gloomhaven uzmanlari kayip kartlari sonlu kaynak olarak yonetir.", quickTips: ["Cop saldiri basina 1 kart kaybet.", "Gec inisiyatif canavar konumuna gore.", "Elementi bir tur once infuse et.", "Uzun dinlenmede max 2 kart kaybi."], strategy: ["Senaryo basina 6-8 kart butcesi.", "Gec inisiyatif AoE icin.", "Element N'de, bonus N+1'de.", "Uzun dinlenme %50 altinda.", "Spellweaver+Cragheart sinerjisi.", "4+ kart kaybinda senaryoyu birak."] },
    { metaDescription: "Gloomhaven-Expertenstrategie: Initiative und Loss-Card-Economy.", intro: "Gloomhaven-Experten behandeln Loss Cards als endliche Ressource.", quickTips: ["Max 1 Loss pro Trash-Attack.", "Spaete Initiative fuer AoE.", "Element Runde vorher infusen.", "2 Loss max pro Long-Rest."], strategy: ["6-8 Loss Budget pro Szenario.", "Late Initiative 80+.", "Element N fuer Bonus N+1.", "Long Rest unter 50% HP.", "Spellweaver+Cragheart.", "Szenario aufgeben bei 4+ Loss."] }
  ),

  frosthaven: g("cooperative-games", "complicated",
    { metaDescription: "Expert Frosthaven: crafting resource loops, town prosperity investment, and scenario modifier exploitation.", intro: "Frosthaven adds crafting and town meta between scenarios. Experts invest prosperity early and craft items that break specific scenario modifiers.", quickTips: ["Invest prosperity before buying gear—unlocks better shop.", "Craft scenario-specific items before entering.", "Masteries: complete bonus objectives for retirement upgrades.", "Don't retire until mastery and prosperity goals met."], strategy: ["Prosperity investment: +1 prosperity before any gear purchase—each level unlocks better shop tier permanently.", "Crafting loops: identify scenario modifier (cold, traps, shields) and craft counter-item before scenario—entering unprepared costs 2+ loss cards.", "Mastery sequencing: complete mastery on first attempt; failing mastery blocks retirement upgrade permanently for that class.", "Town event optimization: choose events that add crafting materials over gold—materials compound, gold doesn't.", "Class retirement timing: retire at level 5 with mastery, not level 3—level 5 unlocks full perk tree for next class.", "Scenario modifier exploitation: some modifiers help players (fog = monsters can't target at range)—choose scenarios matching your party strength."] },
    { metaDescription: "Uzman Frosthaven: zanaat dongusu ve kasaba refah yatirimi.", intro: "Frosthaven senaryolar arasi zanaat ve kasaba metasi ekler.", quickTips: ["Ekipmandan once refah yatir.", "Senaryoya ozel esya uret.", "Mastery bonus hedeflerini tamamla.", "Mastery olmadan emekli olma."], strategy: ["Refah once, ekipman sonra.", "Senaryo modifiyerine karsi esya.", "Mastery ilk denemede.", "Malzeme > altin etkinlikleri.", "Seviye 5'te emeklilik.", "Partiye uygun senaryo sec."] },
    { metaDescription: "Frosthaven-Expertenstrategie: Crafting-Loops und Prosperity.", intro: "Frosthaven ergaenzt Crafting und Town-Meta.", quickTips: ["Prosperity vor Gear.", "Szenario-spezifisch craften.", "Mastery-Bonus erfuellen.", "Nicht ohne Mastery retieren."], strategy: ["Prosperity vor jedem Kauf.", "Counter-Items vor Szenario.", "Mastery beim ersten Versuch.", "Material-Events waehlen.", "Retire bei Level 5.", "Szenario-Modifier ausnutzen."] }
  ),

  "the-crew": g("cooperative-games", "simple",
    { metaDescription: "Expert The Crew: task assignment by hand strength, trump conservation, and communication constraint exploitation.", intro: "The Crew is trick-taking cooperation with limited communication. Experts assign tasks by inferred hand strength and conserve trumps for task completion.", quickTips: ["Strongest hand takes hardest task.", "Conserve trump for your own task tricks.", "Lead low when you want to lose the trick.", "Communication: one card reveal must be permanent signal."], strategy: ["Task assignment: player with most cards in suit X takes task requiring suit X—count dealt cards per suit at start.", "Trump conservation: never trump a trick you can lose—trumps are scarce and needed for your own task.", "Lead signaling: lead your task suit when you want partner to win; lead off-suit when you want to lose.", "Communication optimization: reveal card that permanently signals your task suit or needed suit—never reveal a card you'll play anyway.", "Task ordering: complete easy tasks (low cards) first to free communication; hard tasks (10, A) last when trump is conserved.", "Rocket timing: use rocket only on your own task trick or to save partner's critical task—rocket on random trick wastes win condition."] },
    { metaDescription: "Uzman The Crew: el gucune gore gorev ve koz tasarrufu.", intro: "The Crew sinirli iletisimle isbirlikci kozlu ikidir.", quickTips: ["En guclu el en zor gorevi alir.", "Kozu kendi gorevin icin sakla.", "Kaybetmek icin dusuk oyna.", "Iletisim kalici sinyal olmali."], strategy: ["Dagitimda renk say.", "Koz gereksiz harcanmaz.", "Oncu sinyali ile partneri yonlendir.", "Kalici iletisim karti sec.", "Kolay gorevler once.", "Roket sadece kritik elde."] },
    { metaDescription: "The-Crew-Expertenstrategie: Task-Assignment und Trump-Conservation.", intro: "The Crew ist kooperatives Stichspiel mit begrenzter Kommunikation.", quickTips: ["Staerkste Hand, haerteste Task.", "Trump fuer eigene Tasks.", "Niedrig führen zum Verlieren.", "Kommunikation permanent signalisieren."], strategy: ["Task nach Handstaerke.", "Trump nie verschwenden.", "Lead-Signaling.", "Reveal permanent signalisieren.", "Einfache Tasks zuerst.", "Rocket nur kritisch."] }
  ),

  hanabi: g("cooperative-games", "simple",
    { metaDescription: "Expert Hanabi: clue efficiency, chop line management, and playable card inference from discards.", intro: "Hanabi is information efficiency. Experts maximize clues per point scored and infer playable cards from discard pile and chop line position.", quickTips: ["Clue playability before uniqueness—'playable' clues beat 'these are 3s'.", "Track chop line: card at chop is discarded next fuse loss.", "Conventional hints: left player knows 'newest card is playable' convention.", "Never discard if you might have a playable card."], strategy: ["Clue efficiency: one clue that makes 2+ cards playable beats two clues on single cards—multi-playable clues are gold.", "Chop line management: identify which card hits chop in 1-2 turns; save or play it before fuse loss.", "Discard inference: every discard reveals what numbers are exhausted—if two 3s discarded, your 3 is unique and likely playable.", "Conventional hints protocol: 'playable' clue on newest card; 'not playable' on older cards—table must agree convention round 1.", "Fuse conservation: at fuse 1, only clue playability; never clue color/number without playability confirmation.", "Endgame: with deck empty, play without clues—infer from discards and chop position."] },
    { metaDescription: "Uzman Hanabi: ipucu verimliligi ve chop cizgisi yonetimi.", intro: "Hanabi bilgi verimliligidir. Oynanabilir kart cikarimi chop ve atiktan yapilir.", quickTips: ["Oynanabilirlik ipucusu oncelikli.", "Chop'taki kart sonraki atilacak.", "Konvansiyon: en yeni kart oynanabilir.", "Oynanabilir olabilirse atma."], strategy: ["2+ kart oynatan tek ipucu.", "Chop 1-2 turda kontrol.", "Atiktan sayi cikarimi.", "Masa konvansiyonu R1.", "Fuse 1'de sadece oynanabilirlik.", "Deste bitince cikarimla oyna."] },
    { metaDescription: "Hanabi-Expertenstrategie: Clue-Efficiency und Chop-Line.", intro: "Hanabi ist Informationseffizienz.", quickTips: ["Playability vor Uniqueness.", "Chop-Line tracken.", "Konvention: neueste Karte playable.", "Nie discarden wenn playable moeglich."], strategy: ["Multi-playable Clue.", "Chop in 1-2 Runden.", "Discard-Inference.", "Konvention Runde 1.", "Fuse 1: nur Playability.", "Endgame ohne Clues inferieren."] }
  ),

  "arkham-horror": g("cooperative-games", "complicated",
    { metaDescription: "Expert Arkham Horror: gate compression, clue spending tempo, and mythos mitigation through role specialization.", intro: "Arkham Horror LCG is action economy under mythos pressure. Experts compress gate spawning, spend clues at optimal tempo, and specialize roles for mythos mitigation.", quickTips: ["Close gates before they accumulate—3+ open gates triggers doom.", "Spend clues on investigations, not early evasion.", "Mystic handles spell charges; Guardian handles enemy engagement.", "Mythos phase: mitigate horror before damage."], strategy: ["Gate compression: never let 3+ gates open; each gate adds mythos difficulty. Close gates same round they open when possible.", "Clue tempo: spend clues when investigation skill reaches 4+; hoarding clues past 4 wastes actions on re-investigation.", "Role specialization: Guardian engages and tanks; Mystic evades and spell-damages; Seeker investigates and clues; Rogue evades and resource-generates.", "Mythos mitigation: horror removal before damage—horror kills investigators over 3 rounds; damage is recoverable.", "Scenario objective racing: identify win condition round 1; ignore side objectives that don't advance main goal.", "Card draw engine: Seeker's Old Book of Lore + Dr. Milan Christopher = 2 free actions per turn—invest in draw early."] },
    { metaDescription: "Uzman Arkham Horror: kapi sikistirma ve ipucu harcama temposu.", intro: "Arkham Horror LCG mitos baskisinda aksiyon ekonomisidir.", quickTips: ["3+ acik kapi felaketi tetikler.", "Ipucunu arastirmaya harca.", "Rol uzmanlasmasi sart.", "Once korku, sonra hasar."], strategy: ["Kapilari ayni tur kapat.", "4+ beceride ipucu harca.", "Guardian/Mystic/Seeker/Rogue.", "Korku oncelikli temizlik.", "Ana hedefe odaklan.", "Cekme motoru erken kur."] },
    { metaDescription: "Arkham-Horror-Expertenstrategie: Gate-Compression.", intro: "Arkham Horror LCG ist Action-Economy unter Mythos-Druck.", quickTips: ["3+ Gates vermeiden.", "Clues fuer Investigation.", "Rollen-Spezialisierung.", "Horror vor Damage."], strategy: ["Gates gleiche Runde schliessen.", "Clues bei Skill 4+.", "Guardian/Mystic/Seeker/Rogue.", "Horror-Mitigation.", "Hauptziel R1 identifizieren.", "Draw-Engine frueh."] }
  ),

  "mansions-of-madness": g("cooperative-games", "complicated",
    { metaDescription: "Expert Mansions of Madness: app timing exploitation, investigator role locking, and horror threshold management.", intro: "Mansions of Madness is app-driven exploration with horror thresholds. Experts lock investigator roles early and manage horror before it triggers damage.", quickTips: ["Lock roles round 1: Guardian fights, Seeker investigates, Support heals.", "Horror threshold: rest before reaching damage trigger.", "App timing: move during 'safe' app phases, not combat phases.", "Objective first: ignore loot when objective is one room away."], strategy: ["Role locking: assign combat/support/investigation round 1; switching roles mid-scenario wastes action economy.", "Horror threshold management: rest at horror 3-4, not 5—damage from horror is unrecoverable in short scenarios.", "App phase exploitation: move and investigate during app 'exploration' phases; combat during 'combat' phases—never mix.", "Objective racing: identify objective room round 1; path directly, loot only on path.", "Keeper counter-play (1e): when playing Keeper, spawn monsters on objective path, not random rooms.", "Investigator synergy: Ashcan Pete + Daisy Walker = combat + clue generation without overlap."] },
    { metaDescription: "Uzman Mansions of Madness: rol kilitleme ve korku esigi yonetimi.", intro: "Mansions of Madness uygulama suruculu kesif ve korku esikleridir.", quickTips: ["Rolleri 1. tur kilitle.", "Korku 3-4'te dinlen.", "Guvenli uygulama fazinda hareket.", "Hedefe yakinken ganimet yok."], strategy: ["R1 rol atamasi.", "Korku hasarindan once dinlen.", "Faz bazli hareket.", "Hedef oda R1 belirle.", "Canavar hedef yolunda.", "Pete+Daisy sinerjisi."] },
    { metaDescription: "Mansions-of-Madness-Expertenstrategie: Horror-Threshold.", intro: "Mansions of Madness ist App-getriebene Exploration.", quickTips: ["Rollen R1 locken.", "Rest bei Horror 3-4.", "Bewegen in sicheren Phasen.", "Objective vor Loot."], strategy: ["Role Lock R1.", "Horror vor Damage-Trigger.", "App-Phase-Exploitation.", "Objective-Room R1.", "Monster auf Objective-Path.", "Pete+Daisy-Synergie."] }
  ),

  "flash-point": g("cooperative-games", "simple",
    { metaDescription: "Expert Flash Point: fire spread prediction, specialist action chaining, and victim rescue priority.", intro: "Flash Point is fire spread prediction and specialist chaining. Experts predict flashover triggers and chain Driver + Fire Captain actions.", quickTips: ["Rescue victims before fighting fire—victims score, fire doesn't.", "Fire Captain: extinguish 2 adjacent fires per action.", "Driver: move 2 specialists per action.", "Flashover warning: 4+ fires in room triggers—prevent at 3."], strategy: ["Fire spread prediction: fire spreads to adjacent rooms each turn; map spread 2 turns ahead and pre-position specialists.", "Specialist chaining: Driver moves Fire Captain to hotspot; Fire Captain extinguishes 2; CAFS clears remainder—3 actions, 4+ fires removed.", "Victim priority: rescue victims in flashover-risk rooms first—victim death is loss condition, fire is tempo.", "Flashover prevention: never let room reach 4 fires; at 3 fires, dedicate full turn to that room.", "Structural damage: avoid actions that add structural damage unless victim rescue requires it.", "Endgame: when 4+ victims rescued, shift to fire containment—win is victim count, not fire elimination."] },
    { metaDescription: "Uzman Flash Point: yangin yayilimi tahmini ve uzman zincirleme.", intro: "Flash Point yangin yayilimi tahmini ve uzman zincirlemesidir.", quickTips: ["Kurban kurtarma once.", "Itfaiyeci 2 komsu yangin sondurur.", "Surucu 2 uzman tasir.", "4 yanginda flashover."], strategy: ["2 tur yayilim haritasi.", "Surucu+Itfaiyeci zinciri.", "Flashover riskinde kurtarma.", "3 yanginda odaya odaklan.", "Yapisal hasardan kacinin.", "4 kurban sonra kontrol."] },
    { metaDescription: "Flash-Point-Expertenstrategie: Fire-Spread-Prediction.", intro: "Flash Point ist Brand-Ausbreitungs-Vorhersage.", quickTips: ["Opfer zuerst retten.", "Fire Captain 2 adjacent.", "Driver 2 Spezialisten.", "Flashover bei 4 Feuern."], strategy: ["2-Turn-Spread mappen.", "Driver+Captain-Chain.", "Opfer in Flashover-Rooms.", "Bei 3 Feuern fokussieren.", "Structural Damage vermeiden.", "Ab 4 Opfern: Containment."] }
  ),

  horrified: g("cooperative-games", "simple",
    { metaDescription: "Expert Horrified: monster activation order, item delivery chains, and terror management.", intro: "Horrified is monster activation management and item delivery. Experts sequence monster defeats and chain item deliveries across the map.", quickTips: ["Defeat monsters in activation order—last activated is easiest to isolate.", "Chain item deliveries: pick up 2 items per trip when possible.", "Terror: stay below 5; each monster defeat reduces terror.", "Perk timing: use perks on delivery turns, not movement turns."], strategy: ["Monster activation order: identify which monster activates last; defeat it first while others are dormant.", "Item delivery chains: plan route that picks up 2+ items before delivery—single-item trips waste actions.", "Terror management: terror 5+ triggers loss; defeat one monster to drop terror before pushing to 5.", "Perk optimization: Advanced Actions perk on delivery turn (2 deliveries); Extra Move on multi-item pickup turn.", "Monster-specific tactics: Creature can't enter buildings—lure to open areas; Invisible Man reveals on item pickup.", "Endgame: when 2 monsters remain, focus items for final monster—ignore terror if delivery path is clear."] },
    { metaDescription: "Uzman Horrified: canavar aktivasyon sirasi ve esya teslim zinciri.", intro: "Horrified canavar aktivasyonu ve esya teslimatidir.", quickTips: ["Son aktive olani once yen.", "Tur basina 2 esya topla.", "Terror 5 altinda kal.", "Perk teslimat turunda."], strategy: ["Aktivasyon sirasina gore yen.", "2+ esya rotasi planla.", "Terror 5 oncesi canavar yen.", "Perk tur eslestirmesi.", "Canavara ozel taktik.", "2 canavar kalinca esya odak."] },
    { metaDescription: "Horrified-Expertenstrategie: Monster-Activation-Order.", intro: "Horrified ist Monster-Aktivierung und Item-Delivery.", quickTips: ["Letzten Aktivierten zuerst.", "2 Items pro Trip.", "Terror unter 5.", "Perks auf Delivery-Turns."], strategy: ["Activation-Order-Defeat.", "2+ Item-Route.", "Terror vor 5 senken.", "Perk-Turn-Matching.", "Monster-spezifische Taktik.", "Bei 2 Monstern: Items."] }
  ),

  "robinson-crusoe": g("cooperative-games", "complicated",
    { metaDescription: "Expert Robinson Crusoe: wound management, invention priority, and weather die mitigation.", intro: "Robinson Crusoe is survival action economy. Experts prioritize inventions that reduce weather damage and manage wounds before they compound.", quickTips: ["Shelter + roof before exploring far.", "Wounds compound—heal at 2 wounds, not 3.", "Invention: shovel and map before weapons.", "Weather die: build shelter to reduce weather damage."], strategy: ["Invention priority: Shelter → Roof → Shovel → Map → Weapon. Shovel enables faster resource gathering; map enables exploration.", "Wound management: 2 wounds = -1 action; 3 wounds = death risk. Heal at 2 always.", "Weather die mitigation: roof reduces weather damage by 1; without roof, weather can cost 2+ actions per turn.", "Exploration timing: explore only after shelter+roof+shovel—inadequate prep costs 2+ wounds per exploration.", "Resource conversion: wood → shelter → roof → invention pipeline; don't hoard wood past 3.", "Character specialization: Cook reduces food cost; Carpenter builds faster; Explorer explores safer."] },
    { metaDescription: "Uzman Robinson Crusoe: yara yonetimi ve icat onceligi.", intro: "Robinson Crusoe hayatta kalma aksiyon ekonomisidir.", quickTips: ["Barinak+cati once.", "2 yarada iyilestir.", "Kurek ve harita silahtan once.", "Cati hava hasarini azaltir."], strategy: ["Barinak>cati>kurek>harita.", "2 yarada mutlaka iyilestir.", "Catsiz hava 2+ aksiyon kaybi.", "Hazirliksiz kesif tehlikeli.", "Odun donusum hatti.", "Karakter uzmanlasmasi."] },
    { metaDescription: "Robinson-Crusoe-Expertenstrategie: Wound-Management.", intro: "Robinson Crusoe ist Survival-Action-Economy.", quickTips: ["Shelter+Dach zuerst.", "Bei 2 Wounds heilen.", "Shovel+Map vor Weapons.", "Dach reduziert Weather."], strategy: ["Invention-Priority Shelter>Dach>Shovel.", "Heal bei 2 Wounds.", "Roof fuer Weather.", "Explore nach Shelter+Dach.", "Wood-Pipeline.", "Charakter-Spezialisierung."] }
  ),

  "aeons-end": g("cooperative-games", "complicated",
    { metaDescription: "Expert Aeon's End: breach opening order, spell charge timing, and nemesis turn card manipulation.", intro: "Aeon's End has no shuffle—deck order is knowable. Experts open breaches in optimal order and time spell charges for nemesis turn card breaks.", quickTips: ["Open breaches 1-4 before 5-6—cheaper breaches fund expensive ones.", "Spell charges: hold for nemesis turn card break, not random damage.", "Deck order: count cards—know when Power Ritual comes.", "Focus fire: all mages target same nemesis minion."], strategy: ["Breach opening order: breaches 1-4 cost less; open 1-2 round 1, 3-4 round 2, 5-6 when spells need them.", "Spell charge timing: charge spells to break nemesis turn card (minion spawn, attack)—not for incremental damage.", "Deck order exploitation: no shuffle means card 15 is always Power Ritual—plan 15 turns ahead.", "Nemesis minion focus: all players target same minion—killing one prevents damage; spreading kills none.", "Market composition: buy spells that scale with breaches open; don't buy before breaches ready.", "Mage pairing: Mist + Brama for spell charge generation; Xev for breach opening discount."] },
    { metaDescription: "Uzman Aeon's End: catlak acma sirasi ve buyu sarji zamani.", intro: "Aeon's End karistirmasiz deste sirasidir. Catlaklari sirayla acin, buyu sarjini dusman karti kirmak icin tutun.", quickTips: ["1-4 catlak once.", "Sarji dusman tur karti icin.", "Deste sirasini say.", "Ayni minyona odaklan."], strategy: ["Ucuz catlaklar once.", "Sarj tur karti kirma.", "15. kart her zaman Power Ritual.", "Tek minyon odak.", "Catlak hazir olunca market.", "Mist+Brama sinerjisi."] },
    { metaDescription: "Aeons-End-Expertenstrategie: Breach-Order und Spell-Charge.", intro: "Aeon's End hat kein Shuffle—Deck-Order ist berechenbar.", quickTips: ["Breaches 1-4 zuerst.", "Charges fuer Nemesis-Turn-Break.", "Karten zaehlen.", "Focus Fire auf Minion."], strategy: ["Breach 1-2 R1, 3-4 R2.", "Charge fuer Turn-Card-Break.", "Karte 15 = Power Ritual.", "Gleicher Minion focus.", "Market nach Breaches.", "Mist+Brama-Synergie."] }
  ),

  "marvel-champions": g("cooperative-games", "complicated",
    { metaDescription: "Expert Marvel Champions: threat management, thwart sequencing, and identity-specific resource curves.", intro: "Marvel Champions is threat tempo and thwart sequencing. Experts manage threat before it triggers scheme and sequence thwart for maximum threat reduction per action.", quickTips: ["Thwart before threat hits scheme threshold.", "Identity resource: Spider-Man thwarts, Hulk attacks, Captain Marvel generates resources.", "Defeat minions before they activate.", "Alter-Ego form for resource generation, Hero for damage."], strategy: ["Threat management: thwart when threat is 2 below scheme threshold—waiting until 1 below risks acceleration.", "Thwart sequencing: thwart 2+ threat per action (Black Widow, Spider-Man) beats attack-then-thwart.", "Minion activation: minions activate before villain; defeat minions that deal most damage on activation.", "Alter-Ego/Hero timing: Alter-Ego rounds 1-2 for resource setup; Hero when threat approaches threshold.", "Identity curves: Spider-Man draws + thwarts; Hulk damages + heals; Captain Marvel resource generation.", "Villain phase exploitation: stun villain before villain phase to skip activation—stun timing is win condition."] },
    { metaDescription: "Uzman Marvel Champions: tehdit yonetimi ve engelleme sirasi.", intro: "Marvel Champions tehdit temposu ve engelleme sirasidir.", quickTips: ["Esik oncesi engelle.", "Kimlik kaynak egileri farkli.", "Minyonlari aktivasyondan once yen.", "Alter-Ego kaynak, Hero hasar."], strategy: ["2 altinda engelle.", "Aksiyon basina 2+ engelleme.", "Aktivasyon hasarina gore minyon.", "R1-2 Alter-Ego kurulum.", "Kimlik egileri.", "Bayil ile faz atlama."] },
    { metaDescription: "Marvel-Champions-Expertenstrategie: Threat-Management.", intro: "Marvel Champions ist Threat-Tempo und Thwart-Sequencing.", quickTips: ["Thwart vor Scheme-Threshold.", "Identity-Ressourcen-Kurven.", "Minions vor Activation.", "Alter-Ego fuer Resources."], strategy: ["Thwart 2 unter Threshold.", "2+ Threat pro Action.", "Minion nach Activation-Damage.", "Alter-Ego R1-2.", "Identity-Kurven.", "Stun vor Villain-Phase."] }
  ),

  "lord-of-the-rings-lcg": g("cooperative-games", "complicated",
    { metaDescription: "Expert Lord of the Rings LCG: threat curve management, sphere balancing, and quest stage racing.", intro: "LOTR LCG is threat curve and sphere balance. Experts manage threat growth, balance leadership/lore/spirit/tactics, and race quest stages before threat overwhelms.", quickTips: ["Threat 49 = loss—keep below 40 when possible.", "Sphere balance: each sphere handles different encounter types.", "Quest stage racing: advance before threat spikes.", "Solo spirit for willpower, tactics for combat."], strategy: ["Threat curve: threat grows 1-2 per turn; at 40+, one bad encounter ends game. Thwart/location control threat.", "Sphere balancing: Leadership for resources; Lore for draw; Spirit for willpower; Tactics for combat—mono-sphere fails.", "Quest stage racing: advance quest when threat <35; waiting for perfect board state costs stages.", "Willpower commitment: commit only enough willpower to advance—excess willpower wastes characters.", "Encounter deck forecasting: count encounter cards; when 5 remain, threat spike likely—thwart before final 5.", "Hero pairing: Eowyn (spirit willpower) + Legolas (tactics combat) covers quest + combat."] },
    { metaDescription: "Uzman Lord of the Rings LCG: tehdit egrisi ve kure dengeleme.", intro: "LOTR LCG tehdit egrisi ve kure dengesidir.", quickTips: ["49 tehdit = kayip.", "Kureler farkli karsilasmalari cozer.", "Gorev asamasi yaris.", "Spirit irade, tactics savas."], strategy: ["40 altinda tut.", "Dort kure dengesi.", "35 altinda ilerle.", "Gereken iradeyi ver.", "Son 5 kart oncesi engelle.", "Eowyn+Legolas eslesmesi."] },
    { metaDescription: "LOTR-LCG-Expertenstrategie: Threat-Curve.", intro: "LOTR LCG ist Threat-Curve und Sphere-Balance.", quickTips: ["Threat 49 = Loss.", "Spheres fuer Encounter-Typen.", "Quest-Stage racen.", "Spirit Willpower, Tactics Combat."], strategy: ["Unter 40 halten.", "Vier-Sphere-Balance.", "Advance unter 35.", "Willpower minimal committen.", "Vor letzten 5 Encounter thwarten.", "Eowyn+Legolas-Pairing."] }
  ),

  zombicide: g("cooperative-games", "simple",
    { metaDescription: "Expert Zombicide: noise management, spawn point control, and objective racing before spawn escalation.", intro: "Zombicide is noise management and spawn control. Experts complete objectives before spawn rate escalates and minimize noise to control zombie placement.", quickTips: ["Noise attracts spawns—use silent weapons when possible.", "Complete objectives before spawn rate increases.", "Spawn points: control which zones zombies enter.", "Abominations: focus fire, don't spread damage."], strategy: ["Noise management: each noise token draws spawn; silent kills (knife, crossbow) prevent spawn escalation.", "Spawn point control: position survivors to block spawn zones; zombies spawn in active zones.", "Objective racing: complete 2 objectives before spawn rate hits level 4+—late objectives face 10+ zombies per zone.", "Abomination focus: all survivors target one abomination; spreading damage leaves multiple abominations alive.", "Weapon progression: find better weapons before pushing deep—under-equipped survivors die to lucky spawn.", "Endgame: when 1 objective remains, sacrifice noise for speed—spawn control matters less than completion."] },
    { metaDescription: "Uzman Zombicide: gurultu yonetimi ve dogum noktasi kontrolu.", intro: "Zombicide gurultu ve dogum kontroludur.", quickTips: ["Sessiz silah kullan.", "Dogum hizi artmadan hedefleri bitir.", "Dogum bolgelerini kontrol et.", "Abominationlara odaklan."], strategy: ["Gurultu dogum ceker.", "Aktif bolgeleri blokla.", "Seviye 4 oncesi 2 hedef.", "Tek abomination odagi.", "Ilerlemeden silah bul.", "Son hedefte hiz > gurultu."] },
    { metaDescription: "Zombicide-Expertenstrategie: Noise-Management.", intro: "Zombicide ist Noise-Management und Spawn-Control.", quickTips: ["Stille Waffen nutzen.", "Objectives vor Spawn-Eskalation.", "Spawn-Zonen kontrollieren.", "Abominations fokussieren."], strategy: ["Noise zieht Spawns.", "Spawn-Zonen blocken.", "2 Objectives vor Level 4.", "Focus Fire Abomination.", "Waffen vor Push finden.", "Letztes Objective: Speed."] }
  ),

  "mechs-vs-minions": g("cooperative-games", "complicated",
    { metaDescription: "Expert Mechs vs Minions: command line programming, damage type matching, and schematic ability chaining.", intro: "Mechs vs Minions is command line programming under pressure. Experts program damage type matching and chain schematic abilities for combo turns.", quickTips: ["Match damage type to minion weakness—fire vs ice minions.", "Program 4+ slots before executing—partial programs waste turns.", "Schematic abilities chain—read all before programming.", "Boss phases: save ultimate abilities for phase transitions."], strategy: ["Damage type matching: each minion type has weakness; programming fire against ice minions doubles damage.", "Command line length: 4-slot programs beat 2-slot programs—wait to fill line before execute.", "Schematic chaining: Schematic A enables Schematic B on same turn—read both before programming order.", "Boss phase timing: save ultimate/damage abilities for phase 2-3 transitions when boss is vulnerable.", "Minion priority: kill minions that buff boss before boss—buffed boss costs 2x actions.", "Mech pairing: Ashe + Jinx for fire+ice coverage; Ziggs for AoE on minion swarms."] },
    { metaDescription: "Uzman Mechs vs Minions: komut satiri programlama ve hasar tipi eslestirme.", intro: "Mechs vs Minions baskida komut satiri programlamadir.", quickTips: ["Hasar tipini zayifliga eslestir.", "4+ slot doldur sonra calistir.", "Semalar zincirlenir.", "Ultimate faz gecisinde."], strategy: ["Zayifliga cift hasar.", "4 slotlu program oncelikli.", "Sematik zincirleme.", "Boss fazinda ultimate.", "Buff minyonlari once.", "Ashe+Jinx kapsama."] },
    { metaDescription: "Mechs-vs-Minions-Expertenstrategie: Command-Line-Programming.", intro: "Mechs vs Minions ist Command-Line-Programming unter Druck.", quickTips: ["Damage-Type-Match.", "4+ Slots vor Execute.", "Schematics chainen.", "Ultimate bei Phase-Transition."], strategy: ["Weakness = Doppel-Damage.", "4-Slot-Programme.", "Schematic-Chaining.", "Boss-Phase-Ultimate.", "Buff-Minions zuerst.", "Ashe+Jinx-Coverage."] }
  ),

  "ghost-stories": g("cooperative-games", "complicated",
    { metaDescription: "Expert Ghost Stories: yin/yang balance, Tao token placement, and wu-feng timing.", intro: "Ghost Stories is yin/yang balance and Tao placement. Experts balance exorcism tempo with yin accumulation and place Tao tokens for wu-feng vulnerability windows.", quickTips: ["Yin kills at 4—exorcise before yin accumulates.", "Tao tokens on wu-feng's color weaken him.", "Exorcise ghosts before they reach middle.", "Purple ghosts: exorcise same turn they arrive."], strategy: ["Yin/yang balance: each failed exorcism adds yin; at yin 4, lose. Exorcise before yin 3.", "Tao placement: place Tao on wu-feng's current color before attacking—Tao reduces wu-feng health.", "Ghost arrival priority: ghosts reaching middle board become harder; exorcise at arrival, not after movement.", "Purple ghost rule: purple ghosts activate on arrival—exorcise same turn or face double activation.", "Wu-feng timing: attack wu-feng when Tao count on his color is 3+; below 3, focus ghosts.", "Taoist pairing: yellow (movement) + green (exorcism) for board control + damage."] },
    { metaDescription: "Uzman Ghost Stories: yin/yang dengesi ve Tao yerlestirme.", intro: "Ghost Stories yin/yang dengesi ve Tao yerlestirmedir.", quickTips: ["Yin 4'te kayip.", "Wu-feng rengine Tao koy.", "Ortaya ulasmadan exorcise.", "Mor hayalet ayni tur."], strategy: ["Yin 3 oncesi exorcise.", "Tao wu-feng renginde.", "Varista exorcise.", "Mor ayni tur zorunlu.", "3+ Tao'da wu-feng.", "Sari+yesil eslesmesi."] },
    { metaDescription: "Ghost-Stories-Expertenstrategie: Yin/Yang-Balance.", intro: "Ghost Stories ist Yin/Yang-Balance und Tao-Placement.", quickTips: ["Yin 4 = Loss.", "Tao auf Wu-feng-Farbe.", "Exorcise vor Mitte.", "Purple same turn."], strategy: ["Exorcise vor Yin 3.", "Tao auf Wu-feng-Color.", "Exorcise bei Arrival.", "Purple same turn Pflicht.", "Wu-feng bei 3+ Tao.", "Gelb+Gruen-Pairing."] }
  ),

  "castle-panic": g("cooperative-games", "simple",
    { metaDescription: "Expert Castle Panic: tower segment priority, trade timing, and monster token denial.", intro: "Castle Panic is tower defense with card trading. Experts prioritize tower segments by breach risk and time trades for optimal monster kills.", quickTips: ["Repair breached towers before attacking.", "Trade 1:1 when you need specific color for kill.", "Kill monsters in walls before they reach towers.", "Save Axe for 2-damage kills on strong monsters."], strategy: ["Tower segment priority: center tower breaches lose game fastest; repair center before outer.", "Trade timing: trade when you have 2 of one color and need 1 of another for kill—don't trade for collection.", "Wall kills: monsters in walls are 1 HP; kill before they enter tower zone.", "Axe conservation: Axe does 2 damage; save for Troll/Goblin King, not 1-HP monsters.", "Barter timing: Barter lets trade 2:1; use when hand has 3+ of one color.", "Endgame: when 2 monsters in tower zone, all players focus tower—ignore wall monsters."] },
    { metaDescription: "Uzman Castle Panic: kule segmenti onceligi ve takas zamani.", intro: "Castle Panic kart takasli kule savunmasidir.", quickTips: ["Yarik kuleleri once tamir.", "Oldurmek icin 1:1 takas.", "Duvarlardakileri once yen.", "Balta guclu canavarlara."], strategy: ["Merkez kule oncelikli.", "Oldurme icin takas.", "Duvar 1 can.", "Balta 2 hasar canavarlar.", "Barter 2:1 fazlada.", "Kulede 2 canavar = odak."] },
    { metaDescription: "Castle-Panic-Expertenstrategie: Tower-Segment-Priority.", intro: "Castle Panic ist Tower-Defense mit Karten-Trade.", quickTips: ["Gebrochene Tuerme reparieren.", "Trade 1:1 fuer Kill.", "Wall-Monsters zuerst.", "Axe fuer 2-Damage."], strategy: ["Center-Tower zuerst.", "Trade fuer Kill.", "Wall = 1 HP.", "Axe fuer Troll/King.", "Barter bei 3+ gleicher Farbe.", "2 im Tower = Fokus."] }
  )
};
