/** @typedef {{ metaDescription: string; intro: string; quickTips: [string,string,string,string]; strategy: string[] }} Locale */
/** @param {string} categoryId @param {string} difficulty @param {Locale} en @param {Locale} tr @param {Locale} de @returns {object} */
function g(categoryId, difficulty, en, tr, de) {
  return { categoryId, difficulty, content: { en, tr, de } };
}

/** @type {Record<string, object>} */
export const partyExpert = {
  dixit: g("party-family-games", "simple",
    { metaDescription: "Expert Dixit strategy: rabbit-hole baiting, storyteller ambiguity calibration, and voter herd-breaking.", intro: "Dixit rewards controlled ambiguity. The best storyteller gives clues that fit their card but also plausibly fit 2-3 opponents' cards—never just one.", quickTips: ["Aim for clues that match 2-3 other cards, not zero and not all.", "Never reference a unique visual detail only your card has.", "As voter, avoid the obvious match—storyteller wants the herd on wrong cards.", "Rabbit strategy: vote for the card that 'almost' fits to steal bonus points."], strategy: ["Ambiguity calibration: clue difficulty should scale with table size—4 players need 2-3 matches; 6 players need 3-4.", "Rabbit-hole baiting: reference abstract concepts (loneliness, transition) that map to multiple surreal images.", "Anti-solo clue: if your clue fits only your card, add one word of intentional ambiguity even at risk of missing all votes.", "Voter entropy: never vote first; let others reveal herd direction, then vote the second-best fit.", "Score leader defense: when ahead, give ultra-vague clues—bonus points matter less than not giving rabbits free votes."] },
    { metaDescription: "Uzman Dixit stratejisi: belirsizlik kalibrasyonu ve oy surusu kirma.", intro: "Dixit kontrollu belirsizligi odullendirir. En iyi anlatici kendi kartina ve 2-3 rakip kartina uyan ipuclari verir.", quickTips: ["2-3 karta uyan ipucu hedefleyin.", "Sadece sizin kartinizda olan detaya atif yapmayin.", "Oy verirken bariz eslesmeden kacinin.", "Tavsan stratejisi: neredeyse uyan karta oy verin."], strategy: ["Belirsizlik kalibrasyonu: masa buyudukce ipucu daha genis olmali.", "Soyut kavramlarla coklu eslesme yaratın.", "Tek basina uyan ipucuya kasitli belirsizlik ekleyin.", "Ilk oy vermeyin; suru yonunu gorun.", "Ondeyken ultra belirsiz ipucu verin."] },
    { metaDescription: "Dixit-Expertenstrategie: Mehrdeutigkeits-Kalibrierung und Herden-Brechen.", intro: "Dixit belohnt kontrollierte Mehrdeutigkeit. Der beste Storyteller trifft 2-3 fremde Karten mit.", quickTips: ["Hinweise fuer 2-3 Karten, nicht null oder alle.", "Keine einzigartigen visuellen Details.", "Als Voter die offensichtliche Karte meiden.", "Hase-Strategie: zweitbeste Passung waehlen."], strategy: ["Ambiguitaets-Kalibrierung nach Spielerzahl.", "Rabbit-Hole mit abstrakten Konzepten.", "Anti-Solo-Hinweis mit Absichts-Mehrdeutigkeit.", "Voter-Entropie: nicht zuerst voten.", "Fuehrungs-Defense mit ultra-vagen Hinweisen."] }
  ),

  codenames: g("party-family-games", "simple",
    { metaDescription: "Expert Codenames party play: table tempo, operative trust calibration, and assassin-adjacent cluster denial.", intro: "In party settings, Codenames is won by spymasters who read table culture—literal vs associative players—and calibrate clue entropy to their operatives' guessing style.", quickTips: ["Know your operatives: literal tables need concrete clues; creative tables thrive on abstraction.", "Assassin-adjacent clusters are the #1 loss condition—map them before every clue.", "Clue:2 beats clue:4 when neutrals sit between your targets.", "Use zero clues to reset tempo when operatives are overheating."], strategy: ["Table culture read: first round probe with clue:2 on obvious pairs—operatives' stretch behavior reveals literal vs lateral thinkers.", "Entropy clue design: partition your team's words into tight semantic clusters; a clue touching only your cards beats a clue of +1 that also hits neutral.", "Assassin graph: map 2-hop neighbors of the black card before every clue; FRUIT:3 fails when APPLE is assassin.", "Operative trust calibration: after one bad stretch, switch to clue:1 for two rounds—rebuild trust before another multi-hit.", "Tempo denial: when opponents are one card from win, clue words overlapping their remaining cluster—even as neutral bait on your turn.", "Zero clue meta: burn a turn confirming a link when one wrong guess loses the game."] },
    { metaDescription: "Uzman Codenames parti oyunu: masa kulturu okuma ve suikastci kume reddi.", intro: "Parti ortaminda Codenames, casus liderinin masa kulturunu okumasiyla kazanilir.", quickTips: ["Literal masaya somut, yaratici masaya soyut ipucu.", "Suikastci komsu kumeleri her ipucundan once haritalayin.", "Notrler arasindaki hedeflerde 2'lik ipucu 4'ten iyi.", "Asiri uzama varsa ZERO ile tempo sifirlayin."], strategy: ["Ilk turda clue:2 ile masa kulturunu olcun.", "Sadece takim kartlarina dokunan ipucu tasarlayin.", "Suikastci 2-atim komsularini kontrol edin.", "Kotu uzamadan sonra 2 tur clue:1.", "Rakip kazancina yakin kume cakismasi.", "ZERO ile son oyun kilidi."] },
    { metaDescription: "Codenames-Party-Expertenstrategie: Tischkultur und Attentäter-Cluster.", intro: "Im Party-Kontext gewinnt der Spymaster, der die Tischkultur liest und Entropie kalibriert.", quickTips: ["Literaler Tisch: konkrete Hinweise.", "Attentäter-Cluster vor jedem Hinweis mappen.", "Hinweis:2 schlaegt :4 mit Neutralen dazwischen.", "ZERO bei Overheating der Operatives."], strategy: ["Tischkultur mit clue:2 in Runde 1 sondieren.", "Hinweise nur auf Team-Karten partitionieren.", "Attentäter-2-Hop-Nachbarn pruefen.", "Nach schlechtem Stretch 2 Runden clue:1.", "Tempo-Denial bei Gegner-Win-Threat.", "ZERO-Meta im Endgame."] }
  ),

  wavelength: g("party-family-games", "simple",
    { metaDescription: "Expert Wavelength: spectrum anchoring, opponent psych modeling, and left-right bias correction.", intro: "Wavelength is continuous spectrum estimation. Experts anchor clues to spectrum endpoints and model how each opponent calibrates abstract concepts.", quickTips: ["Anchor to spectrum extremes in your clue, not the middle.", "Know your team's left-right bias—most groups skew toward center.", "Psych clues beat literal clues for abstract spectra (hot-cold, boring-exciting).", "As psychic, give a clue that pins one endpoint, not the target directly."], strategy: ["Spectrum anchoring: 'literally ice' pins cold end; let teammates interpolate. Direct target clues cause center-clustering.", "Team bias correction: track your team's historical offset—if they consistently land 10% right of target, psychic should aim 10% left.", "Opponent psych modeling: in 4v4, read whether opponents use pop-culture vs literal anchors and counter-position your dial.", "Edge spectrum exploitation: on binary-feeling spectra (good-evil), clues at 85% and 15% beat 50% clues that collapse guesses.", "Round 10 leverage: when behind, psychic gives polarizing clues forcing wide spreads—variance favors comeback."] },
    { metaDescription: "Uzman Wavelength: spektrum capalama ve sol-sag onyargi duzeltme.", intro: "Wavelength surekli spektrum tahminidir. Uzmanlar uclara capalar ve takimin onyargisini duzeltir.", quickTips: ["Ipucunu ortaya degil spektrum ucuna capalayin.", "Takimin merkeze kayma egilimini bilin.", "Soyut spektrumlarda psikolojik ipucu literalden iyi.", "Hedefi degil bir uc noktayi sabitleyin."], strategy: ["Uc capalama ile ara deger interpolasyonu.", "Tarihsel sapmayi telafi edin.", "Rakip pop-kultur vs literal okumasi.", "Ikili spektrumlarda %85/%15 ipuclari.", "Gerideyken polarize ipucu ile varyans."] },
    { metaDescription: "Wavelength-Expertenstrategie: Spektrum-Verankerung und Bias-Korrektur.", intro: "Wavelength ist kontinuierliche Spektrum-Schaetzung. Experten verankern an Endpunkten.", quickTips: ["An Spektrumextreme ankern.", "Team-Center-Bias tracken.", "Psych-Hinweise bei abstrakten Spektren.", "Endpunkt statt Ziel direkt cluen."], strategy: ["Endpoint-Anchoring fuer Interpolation.", "Historischen Offset kompensieren.", "Gegner-Psych-Modellierung.", "85/15 bei binaeren Spektren.", "Polarisierung bei Rueckstand."] }
  ),

  telestrations: g("party-family-games", "simple",
    { metaDescription: "Expert Telestrations: misinterpretation seeding, drawable decomposition, and chain-entropy maximization.", intro: "Telestrations winners don't draw well—they draw ambiguously. Seed misinterpretations that compound hilariously while staying recognizable.", quickTips: ["Break phrases into drawable nouns, not abstract concepts.", "Add one ambiguous detail that forks interpretation (hat vs crown).", "Simple shapes beat detailed art under 60-second timer.", "Write guesses that could match multiple drawings—compound the chain."], strategy: ["Misinterpretation seeding: draw the most literal visual of an idiomatic phrase—'break the ice' as cracking ice cube guarantees chain divergence.", "Drawable decomposition: 'happy birthday' → cake with candles, not 'celebration'—nouns survive, adjectives die in translation.", "Ambiguity injection: one extra element (two similar objects) creates fork points that maximize chain entropy.", "Guess optimization: when guessing, pick the most common misread of the drawing, not the most accurate—matches the next player's mental model.", "Chain steering: as drawer, recognize when your chain is 'too accurate' and add deliberate ambiguity to keep point potential high."] },
    { metaDescription: "Uzman Telestrations: yanlis yorum tohumu ve cizilebilir parcalama.", intro: "Telestrations kazananlari iyi cizmez, belirsiz cizer. Zincirde buyuyen yanlis yorumlar tohumlar.", quickTips: ["Soyut degil cizilebilir isimleri secin.", "Yoruma acik bir detay ekleyin.", "60 saniyede basit sekiller detaydan iyi.", "Birden fazla cizime uyan tahmin yazin."], strategy: ["Deyimleri en literal gorselle cizin.", "Sifat yerine isim cizin.", "Cift nesne ile catal noktasi yaratın.", "En yaygin yanlis okumayi tahmin edin.", "Zincir cok dogruysa belirsizlik ekleyin."] },
    { metaDescription: "Telestrations-Expertenstrategie: Fehlinterpretations-Seeding.", intro: "Telestrations-Gewinner zeichnen mehrdeutig, nicht perfekt.", quickTips: ["Drawable Nomen statt Abstraktion.", "Ein mehrdeutiges Detail hinzufuegen.", "Einfache Formen unter 60 Sekunden.", "Guess passend zu mehreren Zeichnungen."], strategy: ["Idiome literal zeichnen.", "Nomen-Ueberlebens-Strategie.", "Ambiguity Injection mit Doppelobjekten.", "Haeufigste Fehllesung raten.", "Deliberate Ambiguity bei zu genauer Kette."] }
  ),

  "the-resistance": g("party-family-games", "simple",
    { metaDescription: "Expert Resistance strategy: mission team composition reads, fail-point optimization, and spy bus timing.", intro: "The Resistance is social deduction on mission composition. Experts read voting patterns for spy tells and optimize which mission to fail as spy.", quickTips: ["Track who proposes teams—they reveal allegiance through inclusion patterns.", "Resistance: never approve a team you can't explain rejecting.", "Spy: fail mission 3, not mission 1—early fails expose you.", "Leader rotation reveals who spies trust."], strategy: ["Vote pattern analysis: spies approve teams containing other spies 85%+ of the time; resistance players show more variance.", "Fail-point optimization (spy): fail on mission 3 or 4 when resistance needs 3 successes—failing mission 1-2 gives too much information.", "Bus timing (spy): when one spy is exposed, the other fails the next mission immediately—coordinate or solo-fail to maximize chaos.", "Resistance team building: include one suspect to gather vote data; reject your own team if spy votes approve unanimously.", "Endgame 2-2: resistance must put only confirmed clean players on final mission—one spy on a 2-person team is 50% fail rate."] },
    { metaDescription: "Uzman Resistance stratejisi: gorev takimi okuma ve casus basma zamani.", intro: "The Resistance gorev kadrosu uzerinden sosyal cikarimdir. Uzmanlar oy desenlerinden casus okur.", quickTips: ["Takim onerenleri takip edin.", "Aciklayamayacaginiz takimi onaylamayin.", "Casus: 1. degil 3. gorevi patlatin.", "Lider rotasyonu casus guvenini gosterir."], strategy: ["Casuslar diger casuslu takimlari cogu zaman onaylar.", "Casus 3-4. gorevi patlatmali.", "Tek casus acilinca digeri hemen patlatir.", "Supheliyi veri icin takima alin.", "2-2'de sadece temiz oyuncu."] },
    { metaDescription: "Resistance-Expertenstrategie: Mission-Team-Reads und Spy-Bus-Timing.", intro: "The Resistance ist Deduktion auf Teamzusammensetzung.", quickTips: ["Team-Vorschlaege tracken.", "Kein Team ohne Ablehnungsbegruendung.", "Spy: Mission 3 failen, nicht 1.", "Leader-Rotation zeigt Spy-Vertrauen."], strategy: ["Spy approven Spy-Teams 85%+.", "Fail-Point auf Mission 3-4.", "Bus-Timing nach Exposure.", "Verdaechtigen fuer Vote-Daten einbinden.", "2-2 nur Clean Players."] }
  ),

  avalon: g("party-family-games", "simple",
    { metaDescription: "Expert Avalon: Merlin protection, Percival decoy reads, and assassin endgame targeting.", intro: "Avalon adds role asymmetry to Resistance. Experts protect Merlin's information advantage while Percival creates intentional ambiguity for the assassin.", quickTips: ["Merlin: never vote perfectly—introduce one 'mistake' per game.", "Percival: react identically to both Merlin candidates until mission 3.", "Assassin: track who looks away when evil wins, not who celebrates.", "Good players: propose teams that force evil to self-identify through rejects."], strategy: ["Merlin camouflage: approve one evil team in missions 1-2 to break perfect-vote tell; assassin hunts consistent approvers.", "Percival decoy: ask both Merlin candidates identical questions; real Merlin answers with slightly more hesitation.", "Assassin endgame: target the player who gives the most information in discussions but votes 'wrong' once—classic Merlin pattern.", "Evil fail timing: same as Resistance but assassin must preserve one evil player for final mission fail.", "Lady of the Lake: pass to players who approved failed missions to confirm evil—not to confirmed good."] },
    { metaDescription: "Uzman Avalon: Merlin koruma ve suikastci hedefleme.", intro: "Avalon rol asimetrisi ekler. Merlin bilgi avantajini korur, Percival kasitli belirsizlik yaratir.", quickTips: ["Merlin mukemmel oy vermesin.", "Percival 3. goreve kadar ayni tepki.", "Suikastci kutlayani degil bakmayani izler.", "Kotulerin kendini ele verecegi takimlar onerin."], strategy: ["Merlin 1-2 kotu takimi onaylar.", "Percival iki adaya ayni soru.", "Suikastci bilgi veren ama bir kez yanlis oylayanı hedefler.", "Kotu patlama zamanlamasi.", "Golet gorevi onaylayanlara verilir."] },
    { metaDescription: "Avalon-Expertenstrategie: Merlin-Schutz und Attentäter-Targeting.", intro: "Avalon ergaenzt Resistance um Rollen-Asymmetrie.", quickTips: ["Merlin nicht perfekt voten.", "Percival identisch bis Mission 3.", "Attentäter trackt Wegschauer.", "Teams die Evil outen erzwingen."], strategy: ["Merlin-Camouflage mit einem Fehlvote.", "Percival-Decoy mit identischen Fragen.", "Attentäter jagt informativen Fehlvoter.", "Evil-Fail-Timing mit Assassin-Preserve.", "Lady an Failed-Mission-Approver."] }
  ),

  werewolf: g("party-family-games", "simple",
    { metaDescription: "Expert Werewolf: night kill priority, seer protection, and villager claim timing.", intro: "Classic Werewolf is night-kill sequencing and day-vote manipulation. Experts prioritize kills that remove information roles without confirming their existence.", quickTips: ["Wolves: kill the quiet analyst, not the loud random player.", "Seer: never reveal night 1—accumulate 3 checks first.", "Villagers: force claims on day 3 when vote math tightens.", "Doctor: self-heal night 1, protect seer night 2 if identified."], strategy: ["Kill priority (wolves): eliminate players who ask structured questions—seer tells are inquiry patterns, not answers.", "Seer hold: reveal only with 3 confirmed wolves or when nominated—early reveal gets you night-killed and confirms seer exists.", "Claim timing: power roles claim on day 3-4 when wolf count is known; day 1 claims are wolf bait.", "Vote block manipulation: coordinate 4-vote bloc on the player wolves want eliminated—wolves steer without revealing.", "Endgame 3-player: seer must share all checks before final vote—silence loses to wolf tie."] },
    { metaDescription: "Uzman Kurt adam: gece oldurme onceligi ve rol aciklama zamani.", intro: "Kurt adam gece oldurme sirasi ve gunduz oy manipulasyonudur.", quickTips: ["Kurtlar sessiz analistci oldurur.", "Gorucu 1. gece aciklamaz.", "3. gunde rol aciklamasi zorla.", "Doktor 1. gece kendini iyilestirir."], strategy: ["Yapilandirilmis soru soranlari hedef alin.", "Gorucu 3 kontrol biriktirir.", "Rol aciklamasi 3-4. gun.", "4 oy blogu ile yonlendirme.", "3 kiside tum kontrolleri paylas."] },
    { metaDescription: "Werewolf-Expertenstrategie: Night-Kill-Priority und Claim-Timing.", intro: "Werewolf ist Nacht-Kill-Sequencing und Tages-Vote-Manipulation.", quickTips: ["Wolves toeten stillen Analysten.", "Seher Nacht 1 nicht offenbaren.", "Claims an Tag 3 erzwingen.", "Doktor self-heal Nacht 1."], strategy: ["Kill Priority auf strukturierte Frager.", "Seher haelt 3 Checks.", "Power-Role-Claims Tag 3-4.", "4-Vote-Block steuern.", "Endgame 3-Player: alle Checks teilen."] }
  ),

  "secret-hitler": g("party-family-games", "simple",
    { metaDescription: "Expert Secret Hitler: policy deck estimation, fascist tracker manipulation, and liberal investigation priority.", intro: "Secret Hitler is policy probability and role deduction. Experts track deck composition, fascist policy placements, and when liberals must investigate vs enact.", quickTips: ["Track enacted policy ratio—deck reshuffles at 5 enacted.", "Fascists: give liberal policies early to earn chancellor trust.", "Liberals: investigate before electing unknown chancellors in 4-5 fascist policy games.", "Hitler never takes obvious fascist policy—watch chancellors who pass clean."], strategy: ["Deck estimation: after 6 policies enacted, calculate remaining fascist/liberal ratio in deck—chancellor picks become deterministic.", "Fascist tracker manipulation: as president, bury fascist policies in discard when possible—reshuffle timing controls election windows.", "Investigation priority: investigate the most electable unknown player, not the most suspicious—electability predicts Hitler risk.", "Hitler camouflage: fascist players give Hitler liberal policies in first 2 governments to build trust for late Hitler chancellorship.", "Endgame 5 fascist policies: liberals must force confirmed liberals as president/chancellor—one Hitler chancellor ends the game."] },
    { metaDescription: "Uzman Secret Hitler: politika destesi tahmini ve fasist izleyici manipulasyonu.", intro: "Secret Hitler politika olasiligi ve rol cikarimidir.", quickTips: ["Cikarilan politika oranini takip edin.", "Fasistler erken liberal politika verir.", "4-5 fasist politikada sorusturma yapin.", "Hitler bariz fasist politika almaz."], strategy: ["6 politika sonrasi deste orani hesaplayin.", "Fasist politikalari cope gomun.", "En secilebilir bilinmeyeni sorusturun.", "Hitler'e erken liberal politika verin.", "5 fasistte sadece dogrulanmis liberal secin."] },
    { metaDescription: "Secret-Hitler-Expertenstrategie: Deck-Schaetzung und Tracker-Manipulation.", intro: "Secret Hitler ist Policy-Wahrscheinlichkeit und Rollen-Deduktion.", quickTips: ["Enacted-Ratio tracken.", "Faschisten geben frueh Liberale.", "Unbekannte Kanzler untersuchen.", "Hitler nimmt keine offensichtlichen Faschisten."], strategy: ["Deck-Schaetzung nach 6 Policies.", "Faschisten-Policies im Discard vergraben.", "Electability vor Suspicion untersuchen.", "Hitler-Camouflage mit Liberalen.", "Endgame: nur bestaetigte Liberale."] }
  ),

  "one-night-ultimate-werewolf": g("party-family-games", "simple",
    { metaDescription: "Expert One Night Ultimate Werewolf: night action sequencing, center card deduction, and zero-information vote bluffing.", intro: "One Night compresses Werewolf into a single night of role swaps and one day of deduction. Experts deduce center cards from night action results and bluff votes.", quickTips: ["Track every night action claim—contradictions reveal center cards.", "Werewolf: claim villager and vote for a villager to split the vote.", "Seer: check center + player, share partial info to bait wolf claims.", "Tanner wins on death—vote Tanner when you want chaos."], strategy: ["Center card deduction: if Robber claims swap with Player A who claims Seer, one center card is likely Werewolf—enumerate possibilities.", "Night action sequencing: Minion sees wolves first; use that info to validate or invalidate wolf claims before voting.", "Zero-information bluff: villagers vote randomly early to force wolves to reveal through defensive claims.", "Role claim pressure: force all players to claim by end of discussion—unclaimed seats are center card candidates.", "Tanner exploitation: when village is split 3-3, vote the Tanner claimer—if wrong, wolves win; if right, Tanner wins and village loses anyway."] },
    { metaDescription: "Uzman One Night Ultimate Werewolf: gece aksiyon sirasi ve merkez kart cikarimi.", intro: "One Night tek gece rol degisimi ve tek gun cikarimdir.", quickTips: ["Her gece iddiasini takip edin.", "Kurt koylu iddia edip koyluye oy verir.", "Gorucu kismi bilgi paylasir.", "Tanner olumle kazanir."], strategy: ["Merkez kart olasiliklarini listele.", "Minion bilgisiyle iddialari dogrula.", "Erken rastgele oy ile kurt cikar.", "Tum oyuncudan rol iddiasi iste.", "Tanner istismari 3-3 bolunmede."] },
    { metaDescription: "One-Night-Werewolf-Expertenstrategie: Center-Card-Deduktion.", intro: "One Night komprimiert Werewolf auf eine Nacht und einen Tag.", quickTips: ["Jede Night-Action-Claim tracken.", "Wolf claimed Villager und splittet Vote.", "Seher teilt partielle Info.", "Tanner gewinnt durch Tod."], strategy: ["Center-Card-Deduktion aus Claims.", "Minion-Info validiert Wolf-Claims.", "Zero-Info-Bluff mit fruehem Vote.", "Role-Claim-Pressure auf alle.", "Tanner-Exploitation bei 3-3-Split."] }
  ),

  "cards-against-humanity": g("party-family-games", "simple",
    { metaDescription: "Expert Cards Against Humanity: judge modeling, card economy, and shock-value calibration for consistent wins.", intro: "CAH is judge psychology, not humor. Experts model each judge's comedy preference and play cards that match their demonstrated taste.", quickTips: ["Read the judge's laugh triggers from previous rounds.", "Play the card that matches the judge's humor tier, not your funniest card.", "Save your best card for a judge who matches your style.", "Two-card plays: pair specific + absurd, not absurd + absurd."], strategy: ["Judge modeling: track whether current judge prefers literal, dark, or absurdist combinations—submit accordingly.", "Card economy: hold 2-3 versatile white cards (nouns that pair broadly) for unknown judges.", "Shock calibration: with conservative judges, witty > shocking; with edgy judges, escalate.", "Pick 2 timing: when black card has two blanks, play specific+wildcard—'My therapist says ___' wants a noun, not a phrase.", "House judge meta: if same judge twice in a row, play their demonstrated favorite archetype from round 1."] },
    { metaDescription: "Uzman Cards Against Humanity: hakem modelleme ve kart ekonomisi.", intro: "CAH hakem psikolojisidir. Uzmanlar her hakemin komedi tercihini modelleyip ona gore kart oynar.", quickTips: ["Hakemin guldugu turleri izleyin.", "En komik degil hakeme uyan karti oynayin.", "En iyi karti uyumlu hakeme saklayin.", "Iki kartta ozellik+absurt eslestirin."], strategy: ["Hakem literal/karanlik/absurt profili cikar.", "2-3 cok yonlu beyaz kart tutun.", "Muhafazakar hakeme sok degil zeka.", "Cift boslukta isim+wildcard.", "Ayni hakem iki turda favori arketip."] },
    { metaDescription: "CAH-Expertenstrategie: Judge-Modelling und Karten-Oekonomie.", intro: "CAH ist Richter-Psychologie. Experten modellieren den Humor des Judges.", quickTips: ["Laugh-Trigger des Judges tracken.", "Passende Karte statt lustigste.", "Beste Karte fuer passenden Judge halten.", "Pick-2: spezifisch+absurd."], strategy: ["Judge-Profil literal/dark/absurd.", "2-3 vielseitige White Cards halten.", "Shock-Calibration nach Judge.", "Pick-2 mit Nomen+Wildcard.", "House-Judge-Meta bei Wiederholung."] }
  ),

  "times-up": g("party-family-games", "simple",
    { metaDescription: "Expert Time's Up: three-round escalation, celebrity tier memorization, and pass-skip optimization.", intro: "Time's Up rewards celebrity familiarity across three escalating constraint rounds. Experts memorize card contents in round 1 for round 3 one-word dominance.", quickTips: ["Round 1: memorize every card pulled—round 3 is one word only.", "Round 2: use exactly one gesture per card, no more.", "Skip obscure cards in round 3; bank time on cards you memorized.", "Team echo: shout partial names early in round 1 to lock memory."], strategy: ["Round 1 memorization: assign each card a unique one-word hook your team agrees on—'Beckham' becomes 'cross' internally.", "Round 2 gesture library: develop 5 standard gestures (sports, movie, politician) that cover 80% of cards.", "Round 3 skip discipline: 3-second skip on unknown cards; 40% of round 3 time is recoverable via skips.", "Celebrity tiering: prioritize memorizing Tier 1 celebrities (Obama, Beckham, Titanic) that appear in multiple games.", "Opponent card denial: in round 1, deliberately slow on cards opponents struggled with—you see their weak spots for round 3."] },
    { metaDescription: "Uzman Time's Up: uc tur yukselisi ve unlu katman ezberi.", intro: "Time's Up uc turda kisitlanan ipucu vermeyi odullendirir. 1. turda kartlari ezberleyin.", quickTips: ["1. turda her karti ezberleyin.", "2. turda kart basina tek jest.", "3. turda bilinmeyeni gecin.", "Kismi isimleri erken bagirin."], strategy: ["Her karta tek kelimelik ic kod verin.", "5 standart jest kutuphanesi kurun.", "3. turda 3 saniyelik pas disiplini.", "Tier 1 unluleri onceliklendirin.", "Rakibin zayif kartlarini 1. turda gozlemleyin."] },
    { metaDescription: "Time's-Up-Expertenstrategie: Drei-Runden-Eskalation.", intro: "Time's Up belohnt Promi-Familiaritaet ueber drei Runden.", quickTips: ["Runde 1: jede Karte memorieren.", "Runde 2: ein Gestus pro Karte.", "Runde 3: Unbekanntes skippen.", "Partielle Namen frueh rufen."], strategy: ["Ein-Wort-Hook pro Karte in R1.", "5-Gesten-Bibliothek in R2.", "Skip-Disziplin in R3.", "Tier-1-Promis priorisieren.", "Gegner-Schwaechen in R1 beobachten."] }
  ),

  mysterium: g("party-family-games", "simple",
    { metaDescription: "Expert Mysterium: ghost vision card sequencing, psychic clue clustering, and final vision tiebreaker reads.", intro: "Mysterium is asymmetric clue-giving under constraint. The ghost must sequence vision cards so psychics build consistent narratives without explicit links.", quickTips: ["Ghost: group vision cards by suspect/location/weapon before dealing.", "Psychics: cluster clues by color and symbol, not by card order.", "Never guess until you have 2+ clues pointing to same card.", "Final vision: ghost gives strongest card first, weakest last."], strategy: ["Ghost sequencing: deal location clues before suspect clues—locations have fewer candidates and anchor deduction.", "Vision card economy: save high-entropy cards (multi-symbol) for ambiguous suspects; single-symbol cards for unique locations.", "Psychic clustering: when 3+ players share a clue symbol, that symbol is likely the correct attribute—coordinate guesses.", "Clover token timing: use on the guess you're 80% confident on, not 50%—wasted clovers lose games.", "Final vision ordering: ghost ranks cards 1-3 by match strength; psychics vote on order, not individual cards."] },
    { metaDescription: "Uzman Mysterium: hayalet vizyon sirasi ve medyum ipucu kumeleri.", intro: "Mysterium kisitli ipucu vermedir. Hayalet vizyonlari tutarli anlatilar icin siralar.", quickTips: ["Hayalet kartlari supheli/mekan/silah olarak grupla.", "Medyumlar renk ve sembole gore kumeler.", "2+ ipucu ayni karta isaret edene kadar tahmin etme.", "Final vizyonda en guclu karti once ver."], strategy: ["Mekan ipuclarini once dagit.", "Yuksek entropi kartlarini belirsiz suphelilere sakla.", "3+ oyuncu ayni sembolu paylasiyorsa dogru olabilir.", "Yonca jetonunu %80 guvende kullan.", "Final sirada guce gore siralama."] },
    { metaDescription: "Mysterium-Expertenstrategie: Ghost-Vision-Sequencing.", intro: "Mysterium ist asymmetrisches Clue-Giving. Der Geist sequenziert Visionen fuer konsistente Narrative.", quickTips: ["Visionen nach Verdaechtigem/Ort/Waffe gruppieren.", "Psychics clustern nach Farbe/Symbol.", "Erst raten bei 2+ Hinweisen.", "Final Vision: staerkste Karte zuerst."], strategy: ["Location-Clues vor Suspect-Clues.", "High-Entropy-Karten fuer ambiguous Suspects.", "Shared-Symbol-Clustering.", "Clover bei 80% Confidence.", "Final-Vision nach Match-Staerke ordnen."] }
  ),

  spyfall: g("party-family-games", "simple",
    { metaDescription: "Expert Spyfall: location question trees, spy entrapment questions, and innocent answer consistency.", intro: "Spyfall is location deduction through targeted questions. Innocents must answer specifically enough to prove knowledge; spies must answer generically enough to hide ignorance.", quickTips: ["Innocents: ask questions only answerable by someone who knows the location.", "Spy: answer with 'it depends' or ask counter-questions to stall.", "Never ask 'how long does it take to get here'—too spy-friendly.", "Vote when one player's answers are consistently location-agnostic."], strategy: ["Location question trees: build 3-hop question chains (transport → activity → equipment) that expose spies who can't maintain consistency.", "Spy entrapment: innocents ask 'what do you do if X happens here'—spies give generic answers; innocents give specific ones.", "Answer specificity: innocents include one location-specific detail per answer (proper noun, local custom)—spies can't fake depth.", "Timer exploitation: spy should ask questions 60% of the time to avoid answering—forces innocents to reveal location through their questions.", "Vote timing: call vote when 2+ players have given agnostic answers; don't wait for certainty—spy wins on time."] },
    { metaDescription: "Uzman Spyfall: mekan soru agaclari ve casus tuzak sorulari.", intro: "Spyfall hedefli sorularla mekan cikarimidir. Masumlar spesifik, casuslar genel cevap verir.", quickTips: ["Masumlar sadece mekani bilenin cevaplayabilecegi soru sorar.", "Casus karsi soru ile zaman kazanir.", "'Buraya ne kadar surer' sorusundan kacinin.", "Surekli genel cevap vereni oylayin."], strategy: ["3 atlama soru zinciri kurun.", "Casus tuzagi: 'burada X olursa ne yaparsin'.", "Her cevapta bir mekan detayi verin.", "Casus %60 soru sorarak konusmadan kacar.", "2+ agnostik cevapta oylamayi cagirin."] },
    { metaDescription: "Spyfall-Expertenstrategie: Location-Question-Trees.", intro: "Spyfall ist Location-Deduktion durch gezielte Fragen.", quickTips: ["Unschuldige stellen ortsspezifische Fragen.", "Spy stellt Gegenfragen.", "Zeitfragen vermeiden.", "Agnostische Antworten voten."], strategy: ["3-Hop-Question-Chains.", "Spy-Entrapment mit Szenario-Fragen.", "Spezifische Details pro Antwort.", "Spy fragt 60% der Zeit.", "Vote bei 2+ agnostischen Antworten."] }
  ),

  "ticket-to-ride": g("party-family-games", "simple",
    { metaDescription: "Expert Ticket to Ride: route blocking, card tempo, and destination risk calibration for family tables.", intro: "At family tables, Ticket to Ride is route denial and card draw tempo. Experts complete short routes early, block longest paths, and manage destination risk.", quickTips: ["Draft 6-8 cards before committing to a color.", "Block the longest unclaimed route segment opponents need.", "Keep at least one short destination for late completion insurance.", "Draw from deck when color you need is visible in face-up row."], strategy: ["Route blocking priority: identify opponents' likely destinations from early station placement; block the bottleneck segment, not the whole route.", "Card tempo: 6-8 card draws before first claim; premature claims telegraph routes and invite blocks.", "Destination risk: hold one 4-6 point destination completable in 3 turns as insurance; long destinations only with 20+ cards in hand.", "Face-up row denial: take cards from face-up even if not needed to deny opponents their color—especially late game.", "Endgame train count: reserve 2-3 trains for a 1-segment completion; running out with incomplete destination is -point swing."] },
    { metaDescription: "Uzman Ticket to Ride: rota bloklama ve kart temposu.", intro: "Aile masasinda Ticket to Ride rota inkari ve kart cekme temposudur.", quickTips: ["Renk secmeden 6-8 kart cekin.", "Rakibin ihtiyac duydugu en uzun segmenti bloklayin.", "Kisa bir destinasyon sigortasi tutun.", "Ihtiyaciniz renk acikta ise desteden cekin."], strategy: ["Dar bogaz segmenti bloklayin.", "Ilk talepten once 6-8 kart.", "4-6 puanlik sigorta destinasyonu.", "Acik kartlari inkar edin.", "Son 2-3 treni 1 segment icin saklayin."] },
    { metaDescription: "Ticket-to-Ride-Expertenstrategie: Route-Blocking und Karten-Tempo.", intro: "Am Familientisch ist TtR Route-Denial und Draw-Tempo.", quickTips: ["6-8 Karten vor Commit.", "Laengstes Segment blocken.", "Kurzes Destination-Insurance halten.", "Vom Deck ziehen bei sichtbarer Farbe."], strategy: ["Bottleneck-Segment blocken.", "6-8 Draws vor erstem Claim.", "4-6-Punkte-Insurance-Destination.", "Face-Up-Denial.", "2-3 Zuege fuer 1-Segment-Endgame."] }
  ),

  "sushi-go": g("party-family-games", "simple",
    { metaDescription: "Expert Sushi Go: draft denial, pudding insurance, and maki count optimization.", intro: "Sushi Go is simultaneous draft with denial. Experts track pudding counts, deny opponent maki ties, and value tempura/sashimi pairs over speculative pudding.", quickTips: ["Count pudding—whoever has least loses 6 points in 4+ player games.", "Take maki to break ties, not to win maki unless you can secure 1st.", "Complete tempura pairs before chasing wasabi-nigiri combos.", "Deny opponents their obvious 3rd sashimi card."], strategy: ["Pudding insurance: in 4-player, ensure you're not last in pudding even if it costs a good card—-6 swing beats +3 from tempura.", "Maki denial: when two players tie for maki lead, draft the 3-maki card to break tie even if you don't want maki—denial is +6 swing.", "Wasabi-nigiri timing: only chase wasabi if you see 2+ nigiri in the draft; single wasabi is -3 net.", "Sashimi completion: opponents' 2nd sashimi is denial priority over your 1st tempura.", "Hand prediction: with 3 cards left in hand, opponents' last picks are predictable—deny their known combo piece."] },
    { metaDescription: "Uzman Sushi Go: draft inkari ve puding sigortasi.", intro: "Sushi Go eszamanli draft ve inkardir. Pudding sayisini takip edin.", quickTips: ["Pudding sayin; son olan -6 yer.", "Maki beraberligi bozmak icin alin.", "Tempura ciftlerini once tamamlayin.", "Rakibin 3. sashimisini engelleyin."], strategy: ["4 oyuncuda puding sonu olmayin.", "Maki beraberligini 3-maki ile bozun.", "Wasabi sadece 2+ nigiri varsa.", "Rakibin 2. sashimisi oncelikli inkar.", "Son 3 kartta tahminle inkar."] },
    { metaDescription: "Sushi-Go-Expertenstrategie: Draft-Denial und Pudding-Insurance.", intro: "Sushi Go ist simultaner Draft mit Denial.", quickTips: ["Pudding zaehlen; Letzter verliert 6.", "Maki fuer Tie-Break nehmen.", "Tempura-Paare zuerst.", "3. Sashimi des Gegners verweigern."], strategy: ["Pudding-Insurance in 4-Spieler.", "Maki-Denial mit 3-Maki.", "Wasabi nur bei 2+ Nigiri.", "2. Sashimi des Gegners priorisieren.", "Letzte 3 Karten vorhersagen."] }
  ),

  "camel-up": g("party-family-games", "simple",
    { metaDescription: "Expert Camel Up: pyramid betting EV, leg position reads, and oasis/desert tile denial.", intro: "Camel Up is expected-value betting on race outcomes. Experts calculate leg-by-leg win probabilities and bet against the herd on long-shot pyramids.", quickTips: ["Bet on 2nd/3rd place legs, not just winners—payout multipliers favor place bets.", "Place oasis/desert tiles to slow leaders, not trailing camels.", "When camel stack is 3+ high, bet on the bottom camel surging.", "Distribute bets across legs—one big winner bet rarely pays."], strategy: ["Pyramid EV: 4th-place bet at 10:1 has positive EV when leader stack is unstable—calculate stack height vs dice probability.", "Leg position reads: camels on oasis tiles move less; desert tiles cause skips—bet on camels 1 tile behind leaders.", "Herd betting: when table bets heavily on leader, place bet on 2nd—payout multiplier rises and leader stacks collapse often.", "Tile denial: place desert in front of leader's next landing, oasis behind trailing camel—swing leg outcomes.", "Endgame leg: final leg bets should cover 3 camels minimum—winner variance is highest on last leg."] },
    { metaDescription: "Uzman Camel Up: piramit bahis EV ve cöl/vaha karosu.", intro: "Camel Up yaris sonucu beklenen deger bahisidir.", quickTips: ["Sadece birinci degil 2./3. bahis yapin.", "Onculeri yavaslatmak icin karolar.", "3+ yuksek yiginda alt deveye bahis.", "Bahisleri turlara dagitin."], strategy: ["4. bahis 10:1 dengesiz yiginda +EV.", "Vaha/cöl konumuna gore bahis.", "Suru lider bahsine karsi 2. bahis.", "Cöl onunde, vaha geride karolama.", "Son turda en az 3 deveyi kapsa."] },
    { metaDescription: "Camel-Up-Expertenstrategie: Pyramid-Betting-EV.", intro: "Camel Up ist EV-Wetten auf Rennausgaenge.", quickTips: ["Platz-Wetten, nicht nur Sieg.", "Oase/Wueste gegen Fuehrung.", "Bei 3+ Stack auf unteres Kamel.", "Wetten auf Legs verteilen."], strategy: ["4th-Place-EV bei instabilem Stack.", "Leg-Position mit Oase/Wueste.", "Gegen Herde auf 2nd wetten.", "Tile-Denial vor Leader.", "Final Leg: 3 Kamele abdecken."] }
  ),

  kingdomino: g("party-family-games", "simple",
    { metaDescription: "Expert Kingdomino: domino selection order, 5x5 grid crown maximization, and turn-order sacrifice.", intro: "Kingdomino is draft order optimization on a 5x5 grid. Experts sacrifice first pick to get better second domino when crown value difference exceeds 2 points.", quickTips: ["Crown count matters more than territory size—2 crowns beats 10 squares.", "Take domino with most crowns even if terrain doesn't fit perfectly.", "Plan your 5x5 grid before placing—one hole ruins endgame.", "Sacrifice first pick when second domino has 3+ more crowns."], strategy: ["Selection order sacrifice: if domino #1 has 1 crown and #2 has 4, take #3 first to secure #2—net +2 crowns.", "5x5 grid planning: reserve center for flexible terrain; corners for single-terrain dead zones.", "Crown density: target 12+ crowns on 5x5; territory size is tiebreaker, crowns win games.", "Meeple blocking: when tied for turn order, take domino opponent needs for their crown combo.", "Endgame hole prevention: never create unfillable 1x1 gaps—each hole costs ~2 crowns in lost placement."] },
    { metaDescription: "Uzman Kingdomino: domino secim sirasi ve 5x5 tac maksimizasyonu.", intro: "Kingdomino 5x5 izgara uzerinde draft sirasi optimizasyonudur.", quickTips: ["Alan degil tac sayisi onemli.", "Uyumsuz olsa bile en cok tacli domino.", "Yerlestirmeden once 5x5 planla.", "3+ tac farkinda ilk secimi feda et."], strategy: ["Tac farkinda sirayi feda et.", "Merkezi esnek, koseyi olu kullan.", "5x5'te 12+ tac hedefle.", "Rakibin tac combosunu kes.", "1x1 delik olusturma."] },
    { metaDescription: "Kingdomino-Expertenstrategie: Draft-Order und Crown-Maximierung.", intro: "Kingdomino ist Draft-Order-Optimierung auf 5x5.", quickTips: ["Crowns > Territorium.", "Crown-reichsten Domino nehmen.", "5x5 vor Placement planen.", "Ersten Pick opfern bei 3+ Crown-Diff."], strategy: ["Selection-Order-Sacrifice.", "Zentrum flexibel, Ecken tot.", "12+ Crowns auf 5x5.", "Meeple-Blocking auf Crown-Combo.", "Keine 1x1-Luecken."] }
  ),

  takenoko: g("party-family-games", "simple",
    { metaDescription: "Expert Takenoko: objective racing, bamboo growth denial, and panda hunger management.", intro: "Takenoko is objective racing with panda sabotage. Experts rush 3-point objectives early while denying opponents bamboo growth needed for their cards.", quickTips: ["Rush 3-point objectives before opponents can block.", "Move panda to eat opponents' irrigated bamboo, not random plots.", "Irrigate before growing—unirrigated growth is wasted.", "Weather tiles: sun for movement, rain for irrigation, wind for two actions."], strategy: ["Objective racing: complete 2 easy objectives (gardener/panda) before pursuing 3-point plot objectives—early points compound turn advantage.", "Panda denial: track opponents' objective cards; eat bamboo on plots matching their color needs—denial is worth 2-3 points swing.", "Irrigation priority: irrigate 3 plots before any growth action—unirrigated bamboo is vulnerable to panda and scores nothing.", "Weather exploitation: wind tile enables move+grow+eat in one turn—save wind for objective completion turns.", "Emperor objective: when 3-point emperor card appears, rush it—only one player can complete and it ends the round race."] },
    { metaDescription: "Uzman Takenoko: hedef yaris ve bambu buyumesi inkari.", intro: "Takenoko hedef yarisidir. 3 puanlik hedefleri erken alin, rakibin bambusunu yiyin.", quickTips: ["3 puanlik hedefleri once alin.", "Pandayi rakibin suladigi bambuya goturun.", "Buyutmeden once sulayin.", "Hava karolarini hedef turunda kullanin."], strategy: ["Kolay 2 hedefi once bitir.", "Rakip kartina gore bambu ye.", "3 parseli once sulayin.", "Ruzgar karosu combo turu.", "Imparator kartini yaris."] },
    { metaDescription: "Takenoko-Expertenstrategie: Objective-Racing und Panda-Denial.", intro: "Takenoko ist Objective-Racing mit Panda-Sabotage.", quickTips: ["3-Punkte-Objectives frueh.", "Panda frisst irrigierten Gegner-Bamboo.", "Vor Wachstum irrigieren.", "Wetter fuer Objective-Turns."], strategy: ["2 einfache Objectives zuerst.", "Panda-Denial nach Gegner-Karten.", "3 Plots vor Growth irrigieren.", "Wind-Combo-Turns.", "Emperor-Card racen."] }
  ),

  qwirkle: g("party-family-games", "simple",
    { metaDescription: "Expert Qwirkle: Qwirkle setup plays, color vs shape line blocking, and hand management for multi-line scores.", intro: "Qwirkle is spatial line building. Experts set up Qwirkle opportunities (6-tile lines) while blocking opponents' multi-line plays.", quickTips: ["Always check if your tile completes a 6-line Qwirkle before playing elsewhere.", "Block opponents' lines at 5 tiles—they're one away from Qwirkle.", "Hold tiles that could Qwirkle on your next turn.", "Play to open 2+ scoring lines with one tile when possible."], strategy: ["Qwirkle setup: place 4-5 tile lines with one gap matching your hand—complete next turn for 12+ points.", "5-tile block: when opponent's line has 5 tiles, play the blocking tile even if it scores 0—Qwirkle denial is 12-point swing.", "Multi-line plays: one tile touching 2 lines scores both; prioritize placement geometry over single-line length.", "Hand management: keep 2 tiles of same color AND 2 of same shape for flexible Qwirkle completion.", "Endgame tile dump: when bag is empty, play highest-scoring tile even if it sets up opponent—points now beat setup."] },
    { metaDescription: "Uzman Qwirkle: Qwirkle kurulumu ve cizgi bloklama.", intro: "Qwirkle uzamsal cizgi kurmadir. 6'li Qwirkle kurun, rakibi 5'te bloklayin.", quickTips: ["6'li Qwirkle tamamlamayi once kontrol edin.", "5 karolu cizgiyi bloklayin.", "Sonraki tur Qwirkle taslarini tutun.", "Tek tasla 2+ cizgi acin."], strategy: ["4-5 karoluk kurulum yapin.", "5'te blok 12 puanlik swing.", "Coklu cizgi oncelikli.", "Esnek el yonetimi.", "Torba bitince hemen puanla."] },
    { metaDescription: "Qwirkle-Expertenstrategie: Qwirkle-Setup und Line-Blocking.", intro: "Qwirkle ist raeumliches Linien-Bauen.", quickTips: ["6er-Qwirkle zuerst pruefen.", "5er-Linien blocken.", "Qwirkle-Tiles fuer naechste Runde halten.", "Ein Tile, zwei Linien."], strategy: ["4-5-Tile-Setup mit Gap.", "5-Tile-Block = 12-Punkte-Swing.", "Multi-Line-Priority.", "Flexible Hand mit Farbe+Form.", "Endgame: sofort punkten."] }
  ),

  "catan-junior": g("party-family-games", "simple",
    { metaDescription: "Expert Catan Junior: ghost ship blocking, Coco the Parrot rush, and island resource tempo.", intro: "Catan Junior simplifies Catan for kids but experts still optimize ghost ship placement and Coco card rush for consistent wins.", quickTips: ["Move ghost ship to block opponents' best resource island.", "Rush Coco cards early—they compound ship movement advantage.", "Build hideouts on diverse islands, not clustered.", "Trade with the market only when it completes a hideout."], strategy: ["Ghost ship denial: place ship on the island opponents need for their next hideout—blocks resource collection for 1-2 turns.", "Coco rush: prioritize Coco cards over hideouts in rounds 1-3; parrot abilities accelerate all future actions.", "Island diversity: 3 hideouts on 3 islands beats 4 on 2—market trade flexibility and ghost ship resilience.", "Market timing: trade only when 1 resource away from hideout; early trades gift opponents tempo.", "Endgame ship control: with 4 hideouts, ghost ship on leader's sole resource island forces market trades at disadvantage."] },
    { metaDescription: "Uzman Catan Junior: hayalet gemi bloklama ve Coco kart yaris.", intro: "Catan Junior cocuklara uyarlansa da hayalet gemi ve Coco kart optimizasyonu kazandirir.", quickTips: ["Hayalet gemiyi rakibin adasina goturun.", "Coco kartlarini erken alin.", "Adalari cesitlendirin.", "Sadece kulube tamamlayacaksa takas."], strategy: ["Hayalet gemi inkari.", "Coco rush ilk 3 tur.", "3 ada cesitliligi.", "Pazar takasini zamanla.", "Son oyun gemi kontrolu."] },
    { metaDescription: "Catan-Junior-Expertenstrategie: Ghost-Ship-Blocking.", intro: "Catan Junior vereinfacht Catan, aber Ghost-Ship und Coco-Rush entscheiden.", quickTips: ["Ghost Ship auf Gegner-Insel.", "Coco-Karten frueh.", "Insel-Diversitaet.", "Markt nur fuer Hideout-Completion."], strategy: ["Ghost-Ship-Denial.", "Coco-Rush R1-3.", "3-Insel-Diversitaet.", "Market-Timing.", "Endgame-Ship-Control."] }
  ),

  "ticket-to-ride-first-journey": g("party-family-games", "simple",
    { metaDescription: "Expert Ticket to Ride First Journey: ticket completion race, route blocking for kids, and train conservation.", intro: "First Journey is a simplified race to complete tickets. Experts block opponents' visible routes and conserve trains for ticket completion.", quickTips: ["Complete your first ticket before drawing a second.", "Block the central hub routes opponents need.", "Count trains—running out with incomplete ticket loses.", "Take face-up cards matching your ticket colors first."], strategy: ["Ticket sequencing: complete ticket 1 before drawing ticket 2—unfinished tickets are -point risk with no upside.", "Hub blocking: central map junctions connect 3+ routes; blocking one hub denies multiple opponents.", "Train conservation: reserve 3 trains minimum for final ticket segment—kids often run out on last connection.", "Visible route reads: opponents' placed routes reveal ticket destinations—block the 2-segment gap they need.", "Color commitment: commit to one color only after 5+ cards; mixed colors waste draws in short game."] },
    { metaDescription: "Uzman Ticket to Ride First Journey: bilet tamamlama yaris ve tren tasarrufu.", intro: "First Journey bilet tamamlama yarisidir. Gorunur rotalari bloklayin, tren saklayin.", quickTips: ["Ikinci bileti cekmeden birinciyi bitirin.", "Merkez hub rotalarini bloklayin.", "Tren sayisini takip edin.", "Bilet renklerine uygun acik kartlari alin."], strategy: ["Bilet sirasi: 1 sonra 2.", "Hub bloklama.", "3 tren rezervi.", "Gorunur rota okuma.", "5+ karttan sonra renk bagliligi."] },
    { metaDescription: "TtR-First-Journey-Expertenstrategie: Ticket-Race.", intro: "First Journey ist vereinfachtes Ticket-Rennen.", quickTips: ["Ticket 1 vor Ticket 2.", "Hub-Routen blocken.", "Zuege zaehlen.", "Face-Up passend zu Tickets."], strategy: ["Ticket-Sequencing.", "Hub-Blocking.", "3-Zug-Reserve.", "Visible-Route-Reads.", "Farb-Commit nach 5+ Karten."] }
  ),

  "hues-and-cues": g("party-family-games", "simple",
    { metaDescription: "Expert Hues and Cues: gamut positioning, saturation anchoring, and opponent color-blindness exploitation.", intro: "Hues and Cues is color gamut communication. Experts anchor clues to gamut extremes and account for how opponents perceive saturation vs hue.", quickTips: ["Clue to gamut edge (darkest, brightest) not the target square.", "Use 'coral' not 'orange' when target is desaturated.", "Track which gamut regions opponents confuse—blues/greens most common.", "Give hue + lightness clue, not hue alone."], strategy: ["Gamut anchoring: 'the darkest blue' pins one axis; teammates interpolate. Direct color names cause center-clustering.", "Saturation calibration: 'dusty rose' vs 'hot pink' distinguishes adjacent squares—hue-only clues fail on pastel regions.", "Confusion zone mapping: most players confuse blue-green boundary; clue toward cyan or navy, never 'teal' without lightness modifier.", "Opponent history: track each player's offset from target—systematic right-shifters need left-anchored clues.", "Round 10: when behind, give polarizing gamut-edge clues forcing wide spreads—variance favors comeback."] },
    { metaDescription: "Uzman Hues and Cues: gamut konumlandirma ve doygunluk capalama.", intro: "Hues and Cues renk gamutu iletisimi. Uclara capalayin, doygunlugu ayirt edin.", quickTips: ["Hedefe degil gamut ucuna ipucu verin.", "Soluk turuncuda 'coral' deyin.", "Mavi-yesil karisikligini bilin.", "Ton + aciklik ipucu verin."], strategy: ["Gamut uc capalama.", "Doygunluk kalibrasyonu.", "Mavi-yesil karmasasindan kacinin.", "Oyuncu sapmasini takip edin.", "Gerideyken polarize ipucu."] },
    { metaDescription: "Hues-and-Cues-Expertenstrategie: Gamut-Positionierung.", intro: "Hues and Cues ist Farb-Gamut-Kommunikation.", quickTips: ["An Gamut-Rand cluen.", "Coral statt Orange bei desaturiert.", "Blau-Gruen-Verwechslung tracken.", "Farbton + Helligkeit."], strategy: ["Gamut-Anchoring.", "Saturation-Calibration.", "Blue-Green-Zone meiden.", "Spieler-Offset tracken.", "Polarisierung bei Rueckstand."] }
  ),

  concept: g("party-family-games", "simple",
    { metaDescription: "Expert Concept: icon layering order, exclusion marking, and concept decomposition for minimal guess rounds.", intro: "Concept is icon-based charades. Experts layer icons from general to specific and mark exclusions early to narrow the guess space.", quickTips: ["Place broad category icons first (living, object, place).", "Mark exclusion icons before adding specific attributes.", "Decompose concept into 3 icon layers: category → attribute → specific.", "Never add a 4th icon before team guesses the first 3 layers."], strategy: ["Icon layering order: category (person) → attribute (fictional) → specific (wizard)—each layer should trigger a guess attempt.", "Exclusion marking: mark 'not real' early when concept is fictional—prevents teammates guessing historical figures.", "Concept decomposition: 'Eiffel Tower' = place + metal + France; never add 'tall' before 'place' is confirmed.", "Guess round minimization: pause after 3 icons for guess; adding icons without guessing wastes cognitive load.", "Opponent disruption: when guessing opponents' concepts, shout broad category guesses to force them to add exclusion icons—burns their turn."] },
    { metaDescription: "Uzman Concept: ikon katman sirasi ve dislama isaretleme.", intro: "Concept ikon tabanli anlatimdir. Genelden ozele katmanlayin, dislamalari erken isaretleyin.", quickTips: ["Once genis kategori ikonlari.", "Ozel nitelikten once dislama isaretle.", "Kategori > nitelik > ozel 3 katman.", "3 ikondan sonra tahmin bekleyin."], strategy: ["Katman sirasi: kisi > kurgusal > buyucu.", "Kurgusalda 'gercek degil' erken isaretle.", "Eyfel = yer + metal + Fransa.", "3 ikonda dur ve tahmin al.", "Rakibe genel tahminle ikon yaktir."] },
    { metaDescription: "Concept-Expertenstrategie: Icon-Layering.", intro: "Concept ist ikon-basiertes Charades.", quickTips: ["Breite Kategorie-Icons zuerst.", "Exclusion vor Spezifischem.", "3 Schichten: Kategorie > Attribut > Spezifisch.", "Nach 3 Icons raten lassen."], strategy: ["Layer-Order Person > Fiktiv > Wizard.", "Exclusion frueh bei Fiktion.", "Eiffelturm = Ort + Metall + Frankreich.", "Pause nach 3 Icons.", "Gegner mit breitem Guess stoeren."] }
  ),

  "doodle-dash": g("party-family-games", "simple",
    { metaDescription: "Expert Doodle Dash: shape-first drawing, category-specific shortcuts, and guess-before-complete racing.", intro: "Doodle Dash is speed Pictionary. Experts use category-specific shape shortcuts and trigger guesses before finishing drawings.", quickTips: ["Draw the most recognizable silhouette first, not details.", "Animals: ears and tail first. Objects: outline first.", "Shout guesses while drawing—team can guess incomplete drawings.", "Skip cards with un drawable abstract concepts immediately."], strategy: ["Shape-first protocol: 3-stroke silhouette triggers guess; details only if no guess in 5 seconds.", "Category shortcuts: animals=get ears; vehicles=get wheels; food=get round shape—train 5 shortcuts per category.", "Guess-before-complete: teammates should guess at 40% completion; drawer adds confirming stroke only.", "Skip discipline: abstract cards ('happiness', 'idea') get 2-second attempt then skip—recover 8 seconds.", "Round pacing: aim for 6 cards per 60 seconds; card 5-6 should be aggressive skips if behind."] },
    { metaDescription: "Uzman Doodle Dash: sekil-oncelikli cizim ve kategori kisayollari.", intro: "Doodle Dash hizli Pictionary. Silueti once cizin, tamamlanmadan tahmin tetikleyin.", quickTips: ["Once en taninir siluet.", "Hayvan: kulak ve kuyruk. Nesne: kontur.", "Cizerken tahmin bagirin.", "Soyut kartlari hemen gecin."], strategy: ["3 vurus siluet protokolu.", "Kategori basina 5 kisayol.", "%40 tamamlaninca tahmin.", "Soyutta 2 saniye sonra pas.", "Dakikada 6 kart hedefi."] },
    { metaDescription: "Doodle-Dash-Expertenstrategie: Shape-First-Drawing.", intro: "Doodle Dash ist Speed-Pictionary.", quickTips: ["Silhouette zuerst.", "Tiere: Ohren+Schwanz.", "Waehrend Zeichnen raten.", "Abstrakte Karten skippen."], strategy: ["3-Stroke-Silhouette.", "5 Shortcuts pro Kategorie.", "Guess bei 40% Completion.", "2-Sekunden-Skip bei Abstrakt.", "6 Karten/60 Sekunden."] }
  ),

  skull: g("party-family-games", "simple",
    { metaDescription: "Expert Skull: bid escalation, rose timing, and opponent skull placement reads.", intro: "Skull is bluffing on hidden disc stacks. Experts read opponent bid patterns for skull placement and time rose reveals for maximum information.", quickTips: ["Bid one higher than you think is safe, not your maximum.", "Place skull on your own stack early to enable future bluff bids.", "Rose reveals: flip rose only when you need to confirm flower count.", "Never bid on a stack you haven't seen flipped at least once."], strategy: ["Bid escalation: opening bid of 1 gathers info; escalate only when you've seen 2+ stacks flip successfully.", "Skull placement: put skull on your own stack in round 1—enables bluff bids on your stack later when opponents fear your skull.", "Rose timing: reveal rose when opponent bids 3+ on unknown stack—confirms flower count without risking skull.", "Stack reads: players who bid aggressively on others' stacks likely have skull on own stack—avoid bidding on their stack.", "Endgame 2-player: bid exactly opponent's expected flip count minus 1—forces them to overbid or pass."] },
    { metaDescription: "Uzman Skull: teklif yukselisi ve kuru cicek zamani.", intro: "Skull gizli disk yiginlarinda blöftur. Teklif desenlerinden kafatasi okuyun.", quickTips: ["Maksimum degil guvenli+1 teklif verin.", "Kafatasini erken kendi yiginina koyun.", "Gul acilimini bilgi gerektiginde yapin.", "Hic acilmamis yigina teklif vermeyin."], strategy: ["Acilis teklifi 1 bilgi toplar.", "Kafatasi R1 kendi yigininda blöf icin.", "Gul rakip 3+ teklifte acilir.", "Agresif teklifci kendi yigininda kafatasi tasir.", "2 kiside tam-1 teklif."] },
    { metaDescription: "Skull-Expertenstrategie: Bid-Eskalation und Rose-Timing.", intro: "Skull ist Bluffen auf verdeckten Stapeln.", quickTips: ["Sicher+1 bieten.", "Skull frueh auf eigenen Stapel.", "Rose nur bei Info-Bedarf.", "Nie auf ungeflippten Stapel bieten."], strategy: ["Bid 1 sammelt Info.", "Skull R1 auf eigenem Stapel.", "Rose bei Gegner-Bid 3+.", "Aggressive Bidder haben Skull.", "2-Spieler: Bid genau-1."] }
  ),

  "no-thanks": g("party-family-games", "simple",
    { metaDescription: "Expert No Thanks: card valuation by sequence gaps, chip conservation, and endgame penalty avoidance.", intro: "No Thanks is sequential card avoidance with chip economy. Experts value cards by gap-filling potential and conserve chips for endgame penalty avoidance.", quickTips: ["Take cards that fill sequence gaps, not high-value isolated cards.", "Pass when chip cost exceeds card's gap-fill value.", "Conserve 3+ chips for endgame when deck runs out.", "Force opponents to take cards by passing until chip pile is tempting."], strategy: ["Gap valuation: card 7 when you hold 6 and 8 is worth +2 net; card 15 isolated is -15 penalty.", "Chip conservation: never spend last 3 chips on marginal cards—endgame without chips forces bad takes.", "Pass psychology: pass on 12+ cards to build chip pile; opponents take when pile hits 4+ chips.", "Sequence racing: complete 2 sequences of 4+ before pursuing single high cards—sequences score double.", "Endgame deck empty: when deck runs out, take any card that reduces penalty even at 0 chips—penalty avoidance beats chip hoarding."] },
    { metaDescription: "Uzman No Thanks: dizi boslugu degerleme ve jeton tasarrufu.", intro: "No Thanks sirali kart kacinma ve jeton ekonomisidir.", quickTips: ["Dizi boslugu dolduran kartlari alin.", "Jeton maliyeti degeri asinca pas gecin.", "Son oyun icin 3+ jeton saklayin.", "Jeton yigini buyuyene kadar pas gecin."], strategy: ["Bosluk degerlemesi: 6-8 arasi 7 degerli.", "Son 3 jetonu koruyun.", "12+ kartlarda pas psikolojisi.", "4+ ardisik dizi once.", "Deste bitince ceza onleme."] },
    { metaDescription: "No-Thanks-Expertenstrategie: Gap-Valuation.", intro: "No Thanks ist Karten-Vermeidung mit Chip-Oekonomie.", quickTips: ["Karten mit Gap-Fill nehmen.", "Passen wenn Chip-Kosten > Wert.", "3+ Chips fuer Endgame.", "Passen bis Chip-Pile verlockend."], strategy: ["Gap-Valuation 6-8 mit 7.", "Letzte 3 Chips schuetzen.", "Pass-Psychology ab 12.", "2 Sequenzen a 4+ zuerst.", "Deck leer: Penalty vermeiden."] }
  ),

  "for-sale": g("party-family-games", "simple",
    { metaDescription: "Expert For Sale: auction bid calibration, property matching, and coin conservation for high-value properties.", intro: "For Sale splits into auction and matching phases. Experts calibrate auction bids to property tier and conserve coins for matching high-value properties.", quickTips: ["Auction: bid half your coins on tier-1 properties, save for tier-3.", "Matching: play lowest card that still wins the property.", "Never bid all coins in auction—you need matching ammo.", "Count remaining properties to calibrate bid aggression."], strategy: ["Auction tiering: tier-1 (1-10) bid 1-3 coins; tier-2 (11-20) bid 3-5; tier-3 (21-30) bid 5-8—save 10+ coins for matching.", "Coin conservation: never spend last 5 coins in auction; matching phase requires 3+ coins for competitive bids.", "Matching optimization: play card equal to property value minus 1 when opponent has shown lower—minimize card waste.", "Property count tracking: with 4 properties left, bid aggressively on tier-3; with 8 left, conserve.", "Bluff bidding: bid 1 on tier-3 to force opponent overspend, then win tier-2 cheaply."] },
    { metaDescription: "Uzman For Sale: acik artirma kalibrasyonu ve eslestirme optimizasyonu.", intro: "For Sale acik artirma ve eslestirme fazlidir. Jetonlari yuksek degerli mulklere saklayin.", quickTips: ["Tier-1'e yarim jeton, tier-3'e sakla.", "Kazanmak icin en dusuk karti oyna.", "Tum jetonlari acik artirmada harcama.", "Kalan mulk sayisina gore teklif ver."], strategy: ["Tier bazli teklif tablosu.", "Son 5 jetonu koru.", "Eslestirmede deger-1 kart.", "4 mulk kalinca agresif.", "Tier-3'te blöf teklif."] },
    { metaDescription: "For-Sale-Expertenstrategie: Auktions-Kalibrierung.", intro: "For Sale hat Auktions- und Matching-Phase.", quickTips: ["Tier-1 halbe Coins, Tier-3 sparen.", "Niedrigste gewinnende Karte.", "Nie alle Coins in Auktion.", "Verbleibende Properties zaehlen."], strategy: ["Tier-Bidding-Tabelle.", "Letzte 5 Coins schuetzen.", "Matching mit Wert-1-Karte.", "Aggressiv bei 4 Properties.", "Bluff-Bid auf Tier-3."] }
  ),

  "point-salad": g("party-family-games", "simple",
    { metaDescription: "Expert Point Salad: negative point avoidance, combo drafting, and pepper multiplier timing.", intro: "Point Salad is multi-category drafting. Experts avoid negative points ruthlessly and time pepper multipliers for maximum combo scoring.", quickTips: ["Never take a card with negative points unless it completes a 10+ point combo.", "Draft peppers early—they multiply all future scoring.", "Complete one full category before splitting across categories.", "Deny opponents their 3rd card in a scoring category."], strategy: ["Negative point ruthlessness: -2 card needs +4 combo to break even; skip unless it enables 15+ point turn.", "Pepper timing: draft 2 peppers by turn 3; each pepper multiplies all category bonuses for remaining game.", "Category commitment: complete 7-card category for 10 bonus before starting second—partial categories score poorly.", "Denial priority: opponents' 3rd card in a category is denial target over your 1st card in new category.", "Endgame point calculation: before each draft, sum possible combos; draft card that maximizes total, not single category."] },
    { metaDescription: "Uzman Point Salad: negatif puan kacinma ve biber carpani zamani.", intro: "Point Salad cok kategorili drafttir. Negatif puanlardan kacinin, biberleri erken alin.", quickTips: ["Negatif puan ancak 10+ combo icin alinir.", "Biberleri erken draft edin.", "Bir kategoriyi tamamlayin.", "Rakibin 3. kartini engelleyin."], strategy: ["-2 kart +4 combo gerektirir.", "3. tura kadar 2 biber.", "7 kart bonusu once.", "Rakibin 3. karti inkar onceligi.", "Her draftta toplam puan hesapla."] },
    { metaDescription: "Point-Salad-Expertenstrategie: Negative-Punkte und Pepper-Timing.", intro: "Point Salad ist Multi-Kategorie-Draft.", quickTips: ["Negative nur fuer 10+ Combo.", "Peppers frueh draften.", "Eine Kategorie vollenden.", "3. Karte des Gegners verweigern."], strategy: ["-2 braucht +4 Combo.", "2 Peppers bis Runde 3.", "7-Karten-Bonus zuerst.", "Denial auf Gegner-3rd.", "Total-Score pro Draft maximieren."] }
  )
};
