/** @typedef {{ metaDescription: string; intro: string; quickTips: [string,string,string,string]; strategy: string[] }} Locale */
/** @param {string} categoryId @param {string} difficulty @param {Locale} en @param {Locale} tr @param {Locale} de @returns {object} */
function g(categoryId, difficulty, en, tr, de) {
  return { categoryId, difficulty, content: { en, tr, de } };
}

/** @type {Record<string, object>} */
export const strategyWarExpert = {
  risk: g("strategy-war-games", "simple",
    { metaDescription: "Expert Risk: continent lock timing, card trade denial, and fortify path optimization for defense in depth.", intro: "Expert Risk is continent timing and card trade math. Lock continents early for bonus troops, deny opponents' trade timing, and fortify for defense in depth.", quickTips: ["Australia and South America lock with 2 borders—easiest continents.", "Trade cards at 3+ for maximum troop burst.", "Fortify borders, not random territories.", "Break opponent continent locks before they reinforce."], strategy: ["Continent lock timing: Australia (2 borders) and South America (2 borders) lock round 2-3; Europe and North America need 3+ borders—lock only with 4+ troops on each border.", "Card trade denial: count opponent cards; when they have 3+, attack to force trade before they get 5-card bonus.", "Fortify depth: stack 8+ on continent border, 2-3 on interior—spreading 4 on every territory loses to concentrated breakthrough.", "Break priority: break smallest continent lock first (Australia) to deny 2 troops/turn.", "Endgame: when 2 players remain, card trades decide—hoard cards until 5-trade for 15 troops swing."] },
    { metaDescription: "Uzman Risk: kita kilidi zamani ve kart takas inkari.", intro: "Uzman Risk kita zamanlamasi ve kart takas matematigidir.", quickTips: ["Avustralya ve Guney Amerika 2 sinirda kilitlenir.", "3+ kartta takas yap.", "Sinirlari guclendir.", "Rakip kilitlerini kir."], strategy: ["2 sinirli kitalar R2-3.", "3 kartta rakibi saldiriya zorla.", "Sinirda 8+ istif.", "En kucuk kilidi kir.", "2 oyuncuda 5-kart takasi."] },
    { metaDescription: "Risk-Expertenstrategie: Kontinent-Lock-Timing.", intro: "Experten-Risk ist Kontinent-Timing und Karten-Tausch-Math.", quickTips: ["Australien und Suedamerika 2 Grenzen.", "Trade bei 3+ Karten.", "Grenzen verstaerken.", "Gegner-Locks brechen."], strategy: ["2-Grenz-Kontinente R2-3.", "Bei 3 Karten angreifen.", "8+ an Grenze.", "Kleinster Lock zuerst.", "5-Karten-Trade im Endgame."] }
  ),

  "axis-and-allies": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Axis & Allies: IPC income curves, transport shucking, and national objective timing.", intro: "Axis & Allies is IPC economy and transport logistics. Experts maximize income curves, shuck infantry via transports, and time national objectives for income spikes.", quickTips: ["Russia: trade space for time; don't die in round 1.", "Germany: pressure Russia while Japan expands.", "UK: secure Africa IPCs before D-Day.", "US: build transports, not battleships."], strategy: ["IPC income curves: Axis needs round 5-6 income lead; Allies win round 8+ when US production overwhelms. Germany must pressure Russia by round 3.", "Transport shucking: UK/US shuck 4 infantry per transport per turn to Europe—infantry density beats naval investment.", "National objective timing: Japan captures Dutch East Indies round 2 for +10 IPC; Germany holds France round 1 for +5.", "Russia survival: fall back to Moscow perimeter; trading Ukraine for time is correct.", "D-Day timing: Allies land round 5-6 when Germany has 2 fronts; round 4 is too early (insufficient buildup)."] },
    { metaDescription: "Uzman Axis & Allies: IPC gelir egrisi ve transport lojistigi.", intro: "Axis & Allies IPC ekonomisi ve transport lojistigidir.", quickTips: ["Rusya alan-zaman takasi.", "Almanya Rusya baskisi.", "Ingiltere Afrika IPC.", "ABD transport, not gemi."], strategy: ["Eksen 5-6. tur gelir.", "Transport ile 4 piyade/tur.", "Japonya DEI R2.", "Rusya Moskova cevresi.", "D-Day R5-6."] },
    { metaDescription: "Axis-Allies-Expertenstrategie: IPC-Kurven.", intro: "Axis & Allies ist IPC-Oekonomie und Transport-Logistik.", quickTips: ["Russland: Raum fuer Zeit.", "Deutschland: Russland-Druck.", "UK: Afrika-IPCs.", "USA: Transports statt Schlachtschiffe."], strategy: ["Axis-Lead R5-6.", "4 Infanterie/Transport/Turn.", "Japan DEI R2.", "Russland Moskau-Perimeter.", "D-Day R5-6."] }
  ),

  "twilight-struggle": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Twilight Struggle: DEFCON timing, ops/event sequencing, and influence placement for control thresholds.", intro: "Twilight Struggle experts treat DEFCON as a resource. Influence placement targets control thresholds; ops/event sequencing maximizes tempo without triggering nuclear war.", quickTips: ["Never play ops in DEFCON 2 battleground countries.", "Realignment beats coup when you have adjacency advantage.", "Space race: dump bad events, not good ops cards.", "Asia/Africa/Middle East: 2 influence for control, not 3."], strategy: ["DEFCON timing: coup in battleground drops DEFCON; at DEFCON 2, coups are forbidden. Play ops in non-battleground at DEFCON 2; save coups for DEFCON 3+.", "Ops/event sequencing: play event when opponent benefits more; play ops when you need influence. Never waste 4-op card as event when you need 4 influence.", "Control thresholds: 2 influence for control in Asia/Africa/ME; 3 in Europe. Over-investing in Europe bleeds ops.", "Realignment vs coup: realignment when you have 2+ adjacent countries; coup when you need to break control and DEFCON allows.", "Scoring card timing: play scoring when you have ops advantage that turn; never hold scoring card opponent can play.", "DEFCON manipulation: force opponent to coup at DEFCON 2 (they lose) by placing influence in battleground they must answer."] },
    { metaDescription: "Uzman Twilight Struggle: DEFCON zamani ve ops/olay sirasi.", intro: "Twilight Struggle uzmanlari DEFCON'u kaynak olarak yonetir. Kontrol esikleri ve ops/olay sirasi kazanir.", quickTips: ["DEFCON 2'de savas alaninda ops oynama.", "Komsuluk avantajinda yeniden hizalama.", "Kotu olaylari uzaya at.", "Asya/Afrika 2 etki kontrol."], strategy: ["DEFCON 2 savas alani yasak.", "4 ops'u olay olarak harcama.", "Asya/Afrika 2 etki.", "2+ komsuda yeniden hizalama.", "Skor karti ops avantajinda.", "DEFCON 2'de rakibi darbe yapmaya zorla."] },
    { metaDescription: "Twilight-Struggle-Expertenstrategie: DEFCON-Timing.", intro: "Twilight-Struggle-Experten behandeln DEFCON als Ressource.", quickTips: ["Keine Ops in DEFCON 2 Battlegrounds.", "Realignment bei Adjacency.", "Schlechte Events spacen.", "Asien/Afrika 2 Influence."], strategy: ["DEFCON 2: Ops nur Non-Battleground.", "4-Ops nicht als Event.", "2 Influence Asia/Africa.", "Realignment bei 2+ Adjacent.", "Scoring bei Ops-Advantage.", "DEFCON 2 Gegner zu Coup zwingen."] }
  ),

  diplomacy: g("strategy-war-games", "complicated",
    { metaDescription: "Expert Diplomacy: stalemate line construction, support order sequencing, and alliance betrayal timing.", intro: "Diplomacy is negotiation backed by support order math. Experts construct stalemate lines, sequence supports for guaranteed gains, and time betrayals for maximum positional swing.", quickTips: ["Support holds beat unsupported attacks.", "Stalemate lines: 3 units can hold 4 provinces.", "Alliance betrayal: strike when ally is overextended.", "Convoy: army to dislodged sea can convoy."], strategy: ["Stalemate line construction: 3 units in defensive formation hold 4+ provinces; identify stalemate lines before attacking.", "Support order sequencing: A supports B into C only when no enemy support cuts; always check support cut paths.", "Alliance betrayal timing: betray when ally has 2+ units committed elsewhere; betrayal during their attack phase maximizes gain.", "Convoy exploitation: convoy army through dislodged fleet's sea zone—creates unexpected attack vectors.", "Draw negotiation: when 3 powers remain, offer stalemate line to weakest—eliminates them, you fight 1v1.", "Opening theory: France-England alliance vs Germany; Italy-Austria vs Turkey—know standard openings to predict supports."] },
    { metaDescription: "Uzman Diplomacy: beraberlik hatti ve destek emri sirasi.", intro: "Diplomacy muzakere ve destek emri matematigidir.", quickTips: ["Destekli tutma desteksiz saldırıdan iyi.", "3 birim 4 ili tutar.", "Muzak rakibe ihanet.", "Konvoy beklenmedik saldiri."], strategy: ["Beraberlik hatti kur.", "Destek kesme yollarini kontrol et.", "Rakip uzatilmisken ihanet.", "Konvoy ile surpriz.", "3 gucte zayifa beraberlik teklif.", "Standart acilis teorisini bil."] },
    { metaDescription: "Diplomacy-Expertenstrategie: Stalemate-Lines.", intro: "Diplomacy ist Verhandlung plus Support-Order-Math.", quickTips: ["Support Holds schlagen Attacks.", "3 Units halten 4 Provinzen.", "Verrat bei Ueberdehnung.", "Convoy fuer Ueberraschung."], strategy: ["Stalemate-Line bauen.", "Support-Cut-Pfade pruefen.", "Verrat bei Commitment.", "Convoy-Exploitation.", "Draw-Angebot an Schwaechsten.", "Opening-Theory kennen."] }
  ),

  "memoir-44": g("strategy-war-games", "simple",
    { metaDescription: "Expert Memoir '44: card counting, terrain exploitation, and unit activation priority.", intro: "Memoir '44 is card-driven tactics. Experts count cards in the draw pile, exploit terrain for defense, and prioritize unit activation for objective control.", quickTips: ["Count cards—know when armor section is depleted.", "Hills and towns: +1 defense die.", "Activate units that can reach objective this turn.", "Right flank card: often weakest—save for retreat."], strategy: ["Card counting: 6 cards per section; when 2 armor played, 4 remain—plan armor push when opponent's section depleted.", "Terrain exploitation: hills/towns give +1 defense; position infantry on objectives with terrain.", "Activation priority: activate unit that reaches objective or kills key unit; don't activate for movement alone.", "Section card management: left/center/right cards restrict activation; play section card when that flank has best opportunity.", "Ambush timing: ambush when opponent commits 2+ units to attack—wipes their turn.", "Medal racing: 4 medals wins; objective control gives medals—prioritize objectives over kills."] },
    { metaDescription: "Uzman Memoir '44: kart sayimi ve arazi istismari.", intro: "Memoir '44 kart suruculu taktiktir.", quickTips: ["Kart say; zirh bolumu tukenince bil.", "Tepe ve kasaba +1 savunma.", "Hedefe ulasan birimi aktive et.", "Sag kanat karti geri cekilme icin."], strategy: ["6 kart/bolum sayimi.", "Arazide piyade konumla.", "Hedef veya oldurme icin aktive.", "Bolum karti en iyi firsatta.", "2+ birim saldirisinda pusu.", "4 madalya = hedef oncelik."] },
    { metaDescription: "Memoir-44-Expertenstrategie: Card-Counting.", intro: "Memoir '44 ist kartengetriebene Taktik.", quickTips: ["Karten zaehlen.", "Huegel/Stadt +1 Defense.", "Unit die Objective erreicht.", "Right-Flank fuer Retreat."], strategy: ["6 Karten/Sektion.", "Infanterie auf Terrain.", "Activation fuer Objective.", "Sektionskarte bei Chance.", "Ambush bei 2+ Attackern.", "4 Medaillen = Objectives."] }
  ),

  "war-of-the-ring": g("strategy-war-games", "complicated",
    { metaDescription: "Expert War of the Ring: action dice allocation, fellowship progression, and military vs corruption race.", intro: "War of the Ring is action dice economy. Free Peoples race fellowship to Mount Doom while Shadow militarily pressures; experts allocate dice by game phase.", quickTips: ["Fellowship: move when corruption is low, hide when high.", "Shadow: military pressure forces Free Peoples dice to defense.", "Action dice: use character dice for fellowship, army dice for battle.", "Ring progression: each step toward Mordor increases corruption risk."], strategy: ["Action dice allocation: Free Peoples use character dice for fellowship movement, army dice for defense; Shadow uses army dice for conquest, character for hunt.", "Fellowship progression: move fellowship when corruption <3; hide and heal when corruption 4+.", "Military vs corruption race: Shadow wins by conquering 10 points of Free Peoples settlements; Free Peoples win by ring destruction.", "Hunt allocation: Shadow allocates hunt tiles to fellowship path; more tiles = higher corruption on reveal.", "Elven rings: use elven ring abilities before dice roll—action generation compounds.", "Endgame: when fellowship reaches Mordor, Shadow must hunt aggressively; Free Peoples must destroy ring before military loss."] },
    { metaDescription: "Uzman War of the Ring: aksiyon zar tahsisi ve yuzuk yaris.", intro: "War of the Ring aksiyon zar ekonomisidir.", quickTips: ["Dusuk bozulmada hareket.", "Golge askeri baskisi.", "Karakter zari yuzuk, ordu savas.", "Mordor'a adim bozulma riski."], strategy: ["Zar tahsisi faza gore.", "Bozulma 4+ gizlen.", "10 puan askeri vs yuzuk.", "Av karosu yolu.", "Elf halkalari once.", "Mordor'da av baskisi."] },
    { metaDescription: "War-of-the-Ring-Expertenstrategie: Action-Dice.", intro: "War of the Ring ist Action-Dice-Oekonomie.", quickTips: ["Fellowship bei niedriger Corruption.", "Shadow Military-Druck.", "Character fuer Fellowship.", "Schritt Richtung Mordor = Risk."], strategy: ["Dice-Allocation nach Phase.", "Hide bei Corruption 4+.", "10 Punkte vs Ring.", "Hunt-Tiles auf Pfad.", "Elven Rings vor Roll.", "Mordor: aggressive Hunt."] }
  ),

  root: g("strategy-war-games", "complicated",
    { metaDescription: "Expert Root: faction-specific meta, sympathy timing, and coalition denial for Woodland Alliance.", intro: "Root experts play faction-specific metas. Marquise engine-builds, Eyrie decree management, Woodland sympathy bursts, and Vagabond coalition timing each have distinct win paths.", quickTips: ["Marquise: sawmill- recruiter- lodge triangle before warriors.", "Eyrie: never add to decree you can't fulfill.", "Woodland: sympathy before revolt.", "Vagabond: repair then coalition with dominant faction."], strategy: ["Marquise meta: sawmill → recruiter → lodge pipeline; 2 warriors per clearing for control; overbuild before opponents contest.", "Eyrie decree: start with 2-action decree; add only actions you'll repeat every turn; decree crash = elimination.", "Woodland sympathy: spread sympathy to 3+ clearings before revolt; revolt with 2+ sympathy in target clearing.", "Vagabond coalition: repair items, then coalition with faction at 20+ points—they win, you win.", "Cats vs Birds: Marquise contests Eyrie starting clearing round 1; delays Eyrie decree setup.", "Faction denial: when behind, attack leader's key buildings, not random—deny VP engine."] },
    { metaDescription: "Uzman Root: fraksiyon metasi ve Woodland koalisyon inkari.", intro: "Root uzmanlari fraksiyon metasi oynar. Marquise motor, Eyrie kararname, Woodland sempati, Vagabond koalisyon.", quickTips: ["Marquise ucgen motor.", "Eyrie yerine getiremeyecegini ekleme.", "Woodland sempati sonra isyan.", "Vagabond tamir sonra koalisyon."], strategy: ["Marquise testere-isci-kulube.", "Eyrie 2 aksiyon kararname.", "3+ sempati sonra isyan.", "20+ puanli fraksiyonla koalisyon.", "Kediler kus acilisini engeller.", "Liderin motoruna saldir."] },
    { metaDescription: "Root-Expertenstrategie: Faction-Meta.", intro: "Root-Experten spielen Faction-spezifische Metas.", quickTips: ["Marquise: Sawmill-Recruiter-Lodge.", "Eyrie: Decree nur erfuellbar.", "Woodland: Sympathy vor Revolt.", "Vagabond: Repair dann Coalition."], strategy: ["Marquise-Pipeline.", "Eyrie 2-Action-Decree.", "3+ Sympathy vor Revolt.", "Coalition mit 20+ Faction.", "Cats contest Birds R1.", "Leader-Engine angreifen."] }
  ),

  "dune-imperium": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Dune Imperium: water placement for conflict thresholds, alliance card timing, and spice debt management.", intro: "Dune Imperium is water placement for conflict control and alliance card tempo. Experts place water to hit conflict thresholds and time alliance plays for maximum influence.", quickTips: ["Water on conflict: 2 water = 2 troops in conflict.", "Alliance cards: play when you can afford influence cost.", "Spice must flow: borrow spice early, repay with endgame VP.", "Intrigue: combat intrigue wins conflicts; economic intrigue builds engine."], strategy: ["Water placement: 2 water in conflict = 2 troops; place water to reach threshold (4, 6, 8) not spread.", "Conflict threshold: 4/6/8 troops trigger rewards; aim for 2nd place at 6 when you can't win—2nd still scores.", "Alliance timing: play alliance when you have 2+ influence and can afford card cost; early alliances fund late-game.", "Spice debt: borrow 3 spice round 1-2 for key card; repay by round 4 or lose VP.", "Intrigue balance: 1 combat intrigue per conflict; rest economic for solari/recruitment.", "Faction focus: Atreides (draw), Harkonnen (intrigue), Fremen (combat)—pick 2, not 3."] },
    { metaDescription: "Uzman Dune Imperium: su yerlestirme ve ittifak karti zamani.", intro: "Dune Imperium catisma esikleri icin su yerlestirme ve ittifak temposudur.", quickTips: ["2 su = 2 asker.", "Ittifak maliyetini karsilayinca oyna.", "Baharat borcu erken al.", "Savas entrikasi catisma kazanir."], strategy: ["Esik icin su yogunlastir.", "6'da 2. olmak da puan.", "2+ etki ile ittifak.", "R4'e kadar borc ode.", "Catisma basina 1 savas entrikasi.", "2 fraksiyon odak."] },
    { metaDescription: "Dune-Imperium-Expertenstrategie: Water-Placement.", intro: "Dune Imperium ist Water-Placement fuer Conflict-Thresholds.", quickTips: ["2 Water = 2 Truppen.", "Alliance wenn Influence reicht.", "Spice frueh leihen.", "Combat-Intrigue gewinnt."], strategy: ["Water fuer Threshold 4/6/8.", "2nd Place bei 6 scoret.", "Alliance bei 2+ Influence.", "Spice bis R4 zurueck.", "1 Combat-Intrigue/Conflict.", "2 Factions fokussieren."] }
  ),

  "small-world": g("strategy-war-games", "simple",
    { metaDescription: "Expert Small World: race/power combo valuation, decline timing, and region count optimization.", intro: "Small World is race/power combo efficiency and decline timing. Experts value combos by regions held per turn and decline before power is exhausted.", quickTips: ["Combo value: regions held × coins per turn.", "Decline when you can't expand—don't overextend.", "In decline: 1 coin per region, no attacks.", "Avoid contested regions—spread to empty areas."], strategy: ["Combo valuation: Tritons (water) + Flying = 8+ regions; Zombies + Diplomat = slow but steady. Value = regions × turns before decline.", "Decline timing: decline when 2+ regions are contested and you can't conquer new—decline at peak, not after losses.", "In-decline income: 1 coin per region in decline; position decline tokens on high-value regions.", "Region count: 6 regions beats 4 with better combo—quantity over quality in early game.", "Power exhaustion: Skeletons grow on decline; decline Skeletons when at 10+ tokens for maximum final income.", "Endgame: last race should be high-coin (Humans, Sorcerers) for final round scoring."] },
    { metaDescription: "Uzman Small World: irk/guc combo degeri ve gerileme zamani.", intro: "Small World irk/guc verimliligi ve gerileme zamanlamasidir.", quickTips: ["Bolge × tur degeri.", "Genisleyemeyince gerile.", "Gerilemede bolge basina 1 altin.", "Bos bolgelere yayil."], strategy: ["Triton+Ucan 8+ bolge.", "Mucadelede gerile.", "Yuksek degerli bolgelere token.", "6 bolge > 4 bolge.", "Iskelet 10+ token gerile.", "Son irk yuksek altin."] },
    { metaDescription: "Small-World-Expertenstrategie: Combo-Valuation.", intro: "Small World ist Race/Power-Effizienz und Decline-Timing.", quickTips: ["Regionen × Muenzen/Turn.", "Decline wenn kein Expand.", "1 Coin/Region in Decline.", "Leere Regionen bevorzugen."], strategy: ["Tritons+Flying 8+ Regionen.", "Decline bei Contest.", "Decline-Tokens auf High-Value.", "6 Regionen > 4.", "Skeletons bei 10+ Tokens.", "Letzte Race high-coin."] }
  ),

  kemet: g("strategy-war-games", "complicated",
    { metaDescription: "Expert Kemet: pyramid control, power tile acquisition order, and battle card bluffing.", intro: "Kemet is pyramid control and power tile sequencing. Experts control pyramids for prayer points, acquire powers in optimal order, and bluff battle cards.", quickTips: ["Pyramid control: 1 prayer per pyramid level per turn.", "Power tiles: mobility and recruitment before combat.", "Battle cards: bluff retreat when you have high damage.", "Night phase: buy powers before praying."], strategy: ["Pyramid control: 3 pyramids = 3 prayer/turn; contest pyramids before buying expensive powers.", "Power acquisition order: Mobility (2) → Recruitment (2) → Combat (3) → Divine. Mobility enables pyramid contest.", "Battle card bluffing: play Retreat when you have 4+ damage card—opponent expects fight, you avoid losses.", "Night phase sequencing: buy 1 power, then pray; don't pray before buying—powers cost prayer.", "Battle timing: attack when opponent has few units; Kemet rewards aggressive expansion.", "Victory points: 10 VP wins; VP powers (Phoenix, Divine) are endgame, not opening."] },
    { metaDescription: "Uzman Kemet: piramit kontrolu ve guc karosu sirasi.", intro: "Kemet piramit kontrolu ve guc karosu sirasidir.", quickTips: ["Piramit basina dua.", "Hareket ve asker once.", "Yuksek hasarda cekilme blöfü.", "Gece once guc al."], strategy: ["3 piramit = 3 dua.", "Hareket>asker>savas.", "4+ hasarda cekilme blöfü.", "Once guc sonra dua.", "Az birimde saldir.", "10 VP gucler son oyun."] },
    { metaDescription: "Kemet-Expertenstrategie: Pyramid-Control.", intro: "Kemet ist Pyramid-Control und Power-Tile-Sequencing.", quickTips: ["1 Prayer/Pyramid-Level.", "Mobility vor Combat.", "Retreat-Bluff bei 4+ Damage.", "Night: Powers vor Pray."], strategy: ["3 Pyramids = 3 Prayer.", "Mobility>Recruitment>Combat.", "Retreat-Bluff.", "Buy vor Pray.", "Attack bei wenig Units.", "10 VP Powers Endgame."] }
  ),

  "blood-rage": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Blood Rage: clan upgrade pathing, rage allocation, and battle loss scoring.", intro: "Blood Rage rewards controlled battle losses. Experts path clan upgrades for synergy and allocate rage for quests over combat when behind on glory.", quickTips: ["Losing battle with 1 figure = 1 glory; winning with 3 = 1 glory.", "Clan upgrades: ship and axe before warrior count.", "Rage on quests when you can't win battle.", "Yggdrasil: pick upgrades that synergize with clan."], strategy: ["Battle loss scoring: 1 figure in losing battle = 1 glory + 1 figure saved; 3 figures winning = 1 glory. Lose smart.", "Clan upgrade pathing: Ship (2) → Axe (2) → Warrior Count (3) → Special. Ship enables quest completion.", "Rage allocation: 4 rage on quest when battle is unwinnable; 2 rage on battle when you can win with 1 figure.", "Yggdrasil synergy: pick upgrades matching clan (Wolf = combat, Raven = quest).", "Ragnarok timing: when Ragnarok approaches, position 1 figure per province for loss scoring.", "Monster timing: kill monsters for glory when you have axe upgrade; don't contest without."] },
    { metaDescription: "Uzman Blood Rage: klan yukseltme yolu ve ofke tahsisi.", intro: "Blood Rage kontrollu savas kaybini odullendirir.", quickTips: ["1 figur kayip = 1 zafer.", "Gemi ve balta once.", "Kazanamayacaksan goreve ofke.", "Klanla uyumlu Yggdrasil."], strategy: ["Akilli kaybetme.", "Gemi>balta>sayi.", "4 ofke gorev.", "Klan sinerjisi.", "Ragnarok'ta 1 figur/il.", "Balta ile canavar."] },
    { metaDescription: "Blood-Rage-Expertenstrategie: Battle-Loss-Scoring.", intro: "Blood Rage belohnt kontrollierte Battle-Losses.", quickTips: ["1 Figur Loss = 1 Glory.", "Ship und Axe zuerst.", "Rage auf Quests.", "Yggdrasil-Synergie."], strategy: ["Smart Loss: 1 Figur.", "Ship>Axe>Count.", "4 Rage Quest.", "Clan-Synergie.", "Ragnarok 1 Figur/Province.", "Monster mit Axe."] }
  ),

  inis: g("strategy-war-games", "complicated",
    { metaDescription: "Expert Inis: Brenn law card timing, clan token placement, and festival action selection.", intro: "Inis is Brenn law manipulation and clan token area control. Experts time Brenn cards for maximum impact and place tokens for festival action advantage.", quickTips: ["Brenn law: play when it benefits you most, not immediately.", "Clan tokens: 2+ in territory for control.", "Festival: pick action others won't contest.", "Sanctuary: 6 clan figures for victory."], strategy: ["Brenn law timing: hold Brenn card until opponent commits to action; play law that nullifies their plan.", "Clan token placement: 2 tokens = control; place in territories with festivals for action advantage.", "Festival action selection: pick action with fewest opponents (e.g., Movement when others want Combat).", "Sanctuary path: 6 clan figures in sanctuary wins; prioritize sanctuary over territory spread.", "Epic card timing: play epic when it wins festival or blocks opponent epic.", "Seasonal timing: winter favors defense; summer favors expansion—adjust Brenn plays."] },
    { metaDescription: "Uzman Inis: Brenn yasa karti zamani ve klan jetonu.", intro: "Inis Brenn yasa manipulasyonu ve alan kontroludur.", quickTips: ["Brenn'i en cok faydanda oyna.", "2 jeton = kontrol.", "Baskalarinin istemedigi festival aksiyonu.", "6 figur sanctuary'de kazanir."], strategy: ["Rakip commit olunca Brenn.", "Festival bolgelerine jeton.", "Az rakip olan aksiyon.", "Sanctuary 6 figur.", "Epic festival kazandir.", "Kis savunma yaz genisleme."] },
    { metaDescription: "Inis-Expertenstrategie: Brenn-Law-Timing.", intro: "Inis ist Brenn-Law-Manipulation und Token-Control.", quickTips: ["Brenn bei maximalem Nutzen.", "2 Tokens = Control.", "Festival-Action ohne Contest.", "6 Figures in Sanctuary."], strategy: ["Brenn nach Gegner-Commit.", "Tokens in Festival-Territories.", "Action mit wenigsten Gegnern.", "Sanctuary 6 Figures.", "Epic fuer Festival-Win.", "Winter Defense, Summer Expand."] }
  ),

  "twilight-imperium": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Twilight Imperium: strategy card timing, technology pathing, and objective race tempo.", intro: "Twilight Imperium is 8-hour strategy card and technology optimization. Experts time strategy cards for objective windows and path technologies for synergy.", quickTips: ["Strategy cards: pick Trade when you need trade goods; Technology when you need tech.", "Technology: path to War Sun or Dreadnought.", "Objectives: score 2 per round when possible.", "Speaker: pass early to get initiative next round."], strategy: ["Strategy card timing: Leadership when you need command tokens; Technology when tech skip objective; Imperial when you can score 2 objectives.", "Technology pathing: War Sun (2 red, 2 yellow) or Dreadnought (2 blue, 1 red)—pick one path round 2.", "Objective race: public objectives score 1; secret score 1; aim for 2 VP per round from round 4.", "Speaker timing: pass first to become speaker next round—speaker chooses strategy card 1.", "Fleet logistics: carriers + fighters for combat; dreadnoughts for defense.", "Alliance timing: negotiate when 2 players approach 10 VP—eliminate leader together."] },
    { metaDescription: "Uzman Twilight Imperium: strateji karti ve teknoloji yolu.", intro: "Twilight Imperium strateji karti ve teknoloji optimizasyonudur.", quickTips: ["Trade ihtiyacinda Ticaret.", "War Sun veya Dreadnought yolu.", "Tur basina 2 hedef puan.", "Erken pas konusmaci icin."], strategy: ["Liderlik komut jetonu.", "R2 teknoloji yolu sec.", "R4'ten 2 VP/tur.", "Ilk pas konusmaci ol.", "Tasiyici+savasci.", "10 VP'de ittifak."] },
    { metaDescription: "Twilight-Imperium-Expertenstrategie: Strategy-Card-Timing.", intro: "Twilight Imperium ist Strategy-Card- und Tech-Optimierung.", quickTips: ["Trade bei Trade-Goods-Bedarf.", "War Sun oder Dreadnought.", "2 VP/Runde ab R4.", "Frueh passen fuer Speaker."], strategy: ["Leadership fuer Command.", "Tech-Path R2.", "2 VP/Runde R4+.", "First Pass = Speaker.", "Carrier+Fighters.", "Alliance bei 10 VP."] }
  ),

  "star-wars-rebellion": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Star Wars Rebellion: probe droid placement, reputation vs military victory paths, and leader ability chaining.", intro: "Star Wars Rebellion splits Rebel reputation vs military paths. Empire hunts base; Rebels build reputation or military. Experts optimize probe placement and leader chains.", quickTips: ["Rebels: hide base, build reputation.", "Empire: probe to find base.", "Leader abilities chain in combat.", "Reputation 14 = Rebel win; 16 Death Stars = Empire win."], strategy: ["Probe placement (Empire): probe systems adjacent to Rebel activity; probe cards reveal base sector.", "Reputation path (Rebel): complete objectives for reputation; 14 reputation wins without destroying Death Star.", "Military path (Rebel): destroy 2 Death Stars for military win—requires heavy combat investment.", "Leader chaining: Vader + Emperor in space combat; Luke + Leia in ground—abilities stack.", "Base relocation: Rebels move base when probe finds sector; move to opposite map corner.", "Combat resolution: space combat first; ground combat only if space lost—prioritize space leaders."] },
    { metaDescription: "Uzman Star Wars Rebellion: sonda yerlestirme ve itibar yolu.", intro: "Star Wars Rebellion isyanci itibar vs askeri yollari ayirir.", quickTips: ["Isyanci: ussu gizle, itibar kur.", "Imparatorluk: sonda ile bul.", "Lider yetenekleri zincirlenir.", "14 itibar veya 2 Olum Yildizi."], strategy: ["Aktivite komsusuna sonda.", "Hedeflerle itibar.", "2 Olum Yildizi askeri zafer.", "Vader+Imparator uzay.", "Sektor bulununca tasi.", "Once uzay savasi."] },
    { metaDescription: "Star-Wars-Rebellion-Expertenstrategie: Probe-Placement.", intro: "Star Wars Rebellion trennt Reputation vs Military.", quickTips: ["Rebels: Base verstecken.", "Empire: Probe finden.", "Leader-Abilities chainen.", "14 Rep oder 2 Death Stars."], strategy: ["Probe an Rebel-Aktivitaet.", "Objectives fuer Reputation.", "2 Death Stars Military.", "Vader+Emperor Space.", "Base bei Fund verlegen.", "Space vor Ground."] }
  ),

  hive: g("strategy-war-games", "simple",
    { metaDescription: "Expert Hive: queen pinning, mobility piece sacrifice, and endgame grasshopper positioning.", intro: "Hive is piece mobility and queen pinning. Experts pin the opponent queen with beetles, sacrifice mobility pieces for tempo, and position grasshopper for endgame.", quickTips: ["Pin queen with beetle on top—queen can't move.", "Grasshopper jumps in straight lines—endgame piece.", "Spider and ant for mobility; beetle for pinning.", "One Hive rule: never break the connected group."], strategy: ["Queen pinning: beetle on opponent queen = queen immobile; pin before they expand.", "Mobility sacrifice: trade ant for ant to gain tempo; ant moves 3 spaces, highest mobility.", "Grasshopper endgame: grasshopper jumps over pieces—position for final queen surround.", "Piece value: Queen (mobility) > Beetle (pin) > Spider (3-step) > Ant (3-step) > Grasshopper (jump).", "Opening: spider/ant expansion before queen placement; queen placed turn 3-4.", "Endgame: surround opponent queen with 6 pieces; grasshopper delivers final surround from distance."] },
    { metaDescription: "Uzman Hive: kralice sabitleme ve cekirge konumlandirma.", intro: "Hive parca hareketliligi ve kralice sabitlemedir.", quickTips: ["Bocek ile kraliceyi sabitle.", "Cekirge duz cizgide atlar.", "Orumcek ve karinca hareket.", "Kovan kuralini bozma."], strategy: ["Bocek sabitleme.", "Karinca takasi tempo.", "Cekirge son oyun.", "Kralice > bocek > orumcek.", "Kralice 3-4. tur.", "6 parca ile cevrele."] },
    { metaDescription: "Hive-Expertenstrategie: Queen-Pinning.", intro: "Hive ist Piece-Mobility und Queen-Pinning.", quickTips: ["Queen mit Beetle pinnen.", "Grasshopper springt gerade.", "Spider und Ant fuer Mobility.", "One Hive nie brechen."], strategy: ["Beetle auf Gegner-Queen.", "Ant-Tausch fuer Tempo.", "Grasshopper Endgame.", "Queen > Beetle > Spider.", "Queen Turn 3-4.", "6 Pieces surround."] }
  ),

  quoridor: g("strategy-war-games", "simple",
    { metaDescription: "Expert Quoridor: wall placement for path denial, pawn advancement tempo, and wall count conservation.", intro: "Quoridor is pathfinding with wall placement. Experts place walls to maximize opponent path length while conserving walls for endgame.", quickTips: ["Wall placement: force opponent 4+ extra moves.", "Advance pawn when opponent is blocked.", "Conserve 2+ walls for endgame.", "Never wall yourself into longer path."], strategy: ["Wall placement math: wall that adds 4+ moves to opponent path is worth 1 wall; 2-move wall is waste.", "Path denial: place wall to force opponent through your pawn's column—creates block.", "Wall conservation: 10 walls each; use 6-7 by midgame, save 3 for endgame block.", "Pawn tempo: advance when opponent spends turn on wall; 2 pawn moves beat 1 wall.", "Endgame: with 2 walls and pawn 2 from goal, wall opponent's direct path—forces 4+ detour.", "Self-path check: before placing wall, verify your path isn't longer than opponent's."] },
    { metaDescription: "Uzman Quoridor: duvar yerlestirme ve yol inkari.", intro: "Quoridor duvar yerlestirme ile yol bulmadir.", quickTips: ["Rakibe 4+ ekstra hamle.", "Rakip bloklaninca ilerle.", "2+ duvar son oyun icin.", "Kendini uzun yola sokma."], strategy: ["4+ hamle = 1 duvar deger.", "Rakibi kendi sutununa zorla.", "10 duvardan 3 sakla.", "2 piyon > 1 duvar.", "Son 2 duvarla yol kapat.", "Duvar oncesi yol kontrol."] },
    { metaDescription: "Quoridor-Expertenstrategie: Wall-Placement.", intro: "Quoridor ist Pathfinding mit Waenden.", quickTips: ["Wall fuer 4+ Extra-Moves.", "Pawn vor wenn Gegner blockt.", "2+ Walls fuer Endgame.", "Nie sich selbst blocken."], strategy: ["4+ Moves = 1 Wall wert.", "Gegner in eigene Spalte.", "3 von 10 Walls sparen.", "2 Pawn > 1 Wall.", "Endgame 2 Walls blocken.", "Self-Path vor Wall pruefen."] }
  ),

  santorini: g("strategy-war-games", "simple",
    { metaDescription: "Expert Santorini: god power exploitation, build-block sequencing, and domed worker positioning.", intro: "Santorini is 3D movement with god powers. Experts exploit god abilities for build-block sequences and position workers for domed win threats.", quickTips: ["Build before move when blocking opponent win.", "God powers: Athena blocks opponent build adjacent.", "Dome on your level 3 before opponent builds level 3.", "Two workers: one threatens win, one blocks."], strategy: ["Build-block sequencing: if opponent can win next turn, build dome on their level 3 before moving—blocks win.", "God power exploitation: Athena prevents opponent build adjacent; position to block key squares.", "Domed worker positioning: worker on level 2 with build to level 3 = win threat; opponent must block.", "Two-worker coordination: worker A threatens win; worker B blocks opponent's block path.", "Rising tide (if used): level 1 start changes opening—build up faster.", "Endgame: when both have level 2 workers, build-block wins over move-up."] },
    { metaDescription: "Uzman Santorini: tanri gucu ve kubbe yerlestirme.", intro: "Santorini tanri gucleriyle 3D harekettir.", quickTips: ["Rakip kazanacaksa once insa et.", "Athena komsu insayi engeller.", "Rakip 3. kata cikmadan kubbe.", "Biri tehdit biri blok."], strategy: ["Kazanma engelinde kubbe.", "Athena ile kare blok.", "2. katta 3. insa tehdidi.", "Iki iscili koordinasyon.", "Yukselen su hizli insa.", "2. katta insa-blok kazanir."] },
    { metaDescription: "Santorini-Expertenstrategie: God-Power-Exploitation.", intro: "Santorini ist 3D-Bewegung mit God Powers.", quickTips: ["Build vor Move bei Gegner-Win.", "Athena blockt adjacent Build.", "Dome vor Gegner Level 3.", "Zwei Workers: Threat+Block."], strategy: ["Build-Block Dome.", "Athena-Position.", "Level 2 Win-Threat.", "Two-Worker-Coordination.", "Rising Tide schneller Build.", "Build-Block schlaegt Move-Up."] }
  ),

  onitama: g("strategy-war-games", "simple",
    { metaDescription: "Expert Onitama: card rotation prediction, student sacrifice, and master path to temple.", intro: "Onitama is card rotation chess. Experts predict which cards return to opponent, sacrifice students for tempo, and path master to temple.", quickTips: ["Cards rotate: played card goes to opponent.", "Sacrifice student to advance master.", "Master to temple wins; student capture doesn't.", "Track which cards opponent will have next turn."], strategy: ["Card rotation prediction: when you play card X, opponent gets it next turn—don't play cards that give opponent winning move.", "Student sacrifice: move student into capture to free master path—master win > student loss.", "Master pathing: shortest path to opponent temple; 4-5 moves with correct cards.", "Card denial: play card that would win for you but is useless to opponent when they receive it.", "Temple control: occupy center for card flexibility; edge limits movement.", "Endgame: when master 2 from temple, sacrifice both students to clear path."] },
    { metaDescription: "Uzman Onitama: kart rotasyonu ve master yolu.", intro: "Onitama kart rotasyonlu satrancdir.", quickTips: ["Oynanan kart rakibe gider.", "Ogrenci feda et master ilerlesin.", "Master tapinaga ulasinca kazan.", "Rakibin sonraki kartlarini tahmin et."], strategy: ["Rakibe kazandirmayan kart oyna.", "Ogrenci feda master yolu.", "En kisa tapinak yolu.", "Rakibe issiz kart ver.", "Merkez kart esnekligi.", "2 ogrenci feda yol ac."] },
    { metaDescription: "Onitama-Expertenstrategie: Card-Rotation.", intro: "Onitama ist Schach mit Karten-Rotation.", quickTips: ["Gespielte Karte an Gegner.", "Student opfern fuer Master.", "Master zum Temple.", "Gegner-Karten vorhersagen."], strategy: ["Keine Win-Karte an Gegner.", "Student-Sacrifice.", "Kuerzester Temple-Path.", "Nutzlos-Karte an Gegner.", "Center fuer Flexibilitaet.", "2 Students fuer Path."] }
  ),

  tak: g("strategy-war-games", "simple",
    { metaDescription: "Expert Tak: road vs wall win condition, capstone flattening, and piece placement tempo.", intro: "Tak is road or wall victory on a growing board. Experts choose win condition early and use capstone to flatten opponent walls.", quickTips: ["Road: connect opposite edges.", "Wall: stack 3+ pieces in one square.", "Capstone flattens walls to roads.", "Place pieces to block opponent road."], strategy: ["Win condition choice: road is faster on 5x5; wall requires capstone—choose road unless opponent commits to road.", "Capstone timing: flatten opponent wall when it reaches 3 high—prevents wall win.", "Road blocking: place piece to break opponent's shortest path; force 4+ detour.", "Piece tempo: 2 placement moves beat 1 capstone move early; capstone wins endgame.", "Board growth: expand board when opponent's road is 2 from win—adds distance.", "Endgame: with capstone and 2 stones, flatten then road in 2 turns."] },
    { metaDescription: "Uzman Tak: yol vs duvar ve capstone duzlestirme.", intro: "Tak yol veya duvar zaferidir.", quickTips: ["Yol: karsi kenarlari bagla.", "Duvar: 3+ istif.", "Capstone duvari yola cevirir.", "Rakip yolunu blokla."], strategy: ["5x5'te yol daha hizli.", "3 yukseklikte capstone.", "En kisa yolu kir.", "Erken 2 tas > capstone.", "Yol yakinsa tahta buyut.", "Capstone+2 tas son oyun."] },
    { metaDescription: "Tak-Expertenstrategie: Road vs Wall.", intro: "Tak ist Road- oder Wall-Sieg.", quickTips: ["Road: gegenueberliegende Kanten.", "Wall: 3+ Stack.", "Capstone flattet Wall.", "Gegner-Road blocken."], strategy: ["Road schneller auf 5x5.", "Capstone bei 3 High.", "Shortest Path brechen.", "2 Placements > Capstone frueh.", "Board wachsen bei Road-Threat.", "Capstone+2 Stones Endgame."] }
  ),

  yinsh: g("strategy-war-games", "simple",
    { metaDescription: "Expert Yinsh: ring placement for line potential, marker flipping chains, and ring removal timing.", intro: "Yinsh is ring placement and marker flipping. Experts place rings for line potential, chain marker flips, and time ring removal for maximum line clears.", quickTips: ["5 in a row removes ring; 3 rings removed wins.", "Place rings where they create multiple line threats.", "Flip markers to create flip chains.", "Remove ring when it clears 2+ lines."], strategy: ["Ring placement: place ring where 4 markers already align—one move from line.", "Marker flip chains: flip marker that flips adjacent markers—chain flips create multiple lines.", "Ring removal timing: remove ring when it completes 2 lines (removes 2 opponent rings).", "Line threat pressure: create 2 simultaneous line threats—opponent can block one.", "Center control: center rings influence more lines; edge rings are defensive.", "Endgame: with 2 rings, create double line threat; opponent blocks one, you complete other."] },
    { metaDescription: "Uzman Yinsh: halka yerlestirme ve isaretci cevirme zinciri.", intro: "Yinsh halka yerlestirme ve isaretci cevirmedir.", quickTips: ["5'li satir halka kaldirir.", "Coklu tehdit icin halka koy.", "Zincir cevirme yap.", "2+ satir temizlerken halka kaldir."], strategy: ["4 isaretci hizasina halka.", "Zincir cevirme.", "2 satirda halka kaldir.", "Cift tehdit olustur.", "Merkez daha fazla cizgi.", "2 halka cift tehdit."] },
    { metaDescription: "Yinsh-Expertenstrategie: Ring-Placement.", intro: "Yinsh ist Ring-Placement und Marker-Flipping.", quickTips: ["5 in Row entfernt Ring.", "Rings fuer Line-Threats.", "Flip-Chains.", "Ring bei 2+ Lines entfernen."], strategy: ["Ring bei 4 Markern.", "Marker-Flip-Chains.", "Ring bei 2 Lines.", "Double Line Threat.", "Center mehr Lines.", "2 Rings Double Threat."] }
  ),

  tzaar: g("strategy-war-games", "simple",
    { metaDescription: "Expert Tzaar: piece type balance, capture priority, and endgame tzaar preservation.", intro: "Tzaar is capture with piece type balance. Experts maintain tzarrs, tazars, and tots balance while capturing opponent pieces.", quickTips: ["Lose all of one type = loss.", "Capture highest value piece when possible.", "Tzaar (big) > Tazar (medium) > Tot (small).", "Don't sacrifice tzaar for tot."], strategy: ["Piece type balance: never let one type drop to 0; capture opponent's strongest type first.", "Capture priority: tzaar capture removes opponent's strongest; tot capture is tempo.", "Endgame tzaar preservation: with 2 tzaars, never risk both—one tzaar must survive.", "Stack control: pieces on stacks are harder to capture; build stacks defensively.", "Forced capture: when capture available, must capture—use to force opponent into bad captures.", "Endgame: when opponent has 1 of a type, capture it to win—prioritize type elimination."] },
    { metaDescription: "Uzman Tzaar: parca tipi dengesi ve tzaar koruma.", intro: "Tzaar yakalama ve tip dengesidir.", quickTips: ["Bir tip 0 = kayip.", "En yuksek degeri yakala.", "Tzaar > Tazar > Tot.", "Tzaar'i tot icin feda etme."], strategy: ["Tip dengesini koru.", "Tzaar yakalama oncelik.", "2 tzaardan birini koru.", "Istif savunmasi.", "Zorunlu yakalamayi kullan.", "Son tipte kazan."] },
    { metaDescription: "Tzaar-Expertenstrategie: Piece-Type-Balance.", intro: "Tzaar ist Capture mit Typ-Balance.", quickTips: ["0 von einem Typ = Loss.", "Hoechsten Wert capturen.", "Tzaar > Tazar > Tot.", "Tzaar nicht fuer Tot opfern."], strategy: ["Typ-Balance halten.", "Tzaar-Capture priorisieren.", "1 Tzaar ueberleben.", "Stack-Defense.", "Forced Capture nutzen.", "Letzten Typ eliminieren."] }
  ),

  "undaunted-normandy": g("strategy-war-games", "simple",
    { metaDescription: "Expert Undaunted Normandy: deck building tempo, suppression fire, and initiative control.", intro: "Undaunted is deck-building tactics. Experts build lean decks, use suppression to pin opponents, and control initiative for action order.", quickTips: ["Remove weak cards from deck—lean deck cycles faster.", "Suppression pins opponent units.", "Initiative: play initiative card when you need first action.", "Scout reveals opponent hand—plan suppression."], strategy: ["Deck building: remove 1-2 weak cards per scenario; 6-card deck cycles in 3 turns.", "Suppression fire: suppress opponent key unit before they act—pins for 1 turn.", "Initiative control: play initiative when you have kill shot; pass initiative when opponent has weak hand.", "Scout timing: scout before opponent plays—reveals hand for suppression targeting.", "Unit positioning: units in cover take less damage; advance under suppression.", "Endgame: when opponent deck is 3 cards, scout every turn—predictable hand."] },
    { metaDescription: "Uzman Undaunted Normandy: deste kurma ve baskilama atesi.", intro: "Undaunted deste kurma taktigidir.", quickTips: ["Zayif kartlari cikar.", "Baskilama birimi sabitler.", "Inisiyatif ilk aksiyon icin.", "Kesif rakip elini gosterir."], strategy: ["6 kartlik ince deste.", "Ana birimi baskila.", "Oldurme atisinda inisiyatif.", "Oynamadan once kesif.", "Siper hasar azaltir.", "3 kartli elde kesif."] },
    { metaDescription: "Undaunted-Normandy-Expertenstrategie: Deck-Building.", intro: "Undaunted ist Deck-Building-Taktik.", quickTips: ["Schwache Karten entfernen.", "Suppression pinnt Units.", "Initiative fuer erste Action.", "Scout zeigt Hand."], strategy: ["6-Card Lean Deck.", "Key Unit suppressen.", "Initiative bei Kill-Shot.", "Scout vor Gegner-Play.", "Cover reduziert Damage.", "Scout bei 3-Card-Deck."] }
  ),

  "commands-and-colors": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Commands & Colors: card play for battle back, terrain line exploitation, and weakened flank targeting.", intro: "Commands & Colors is card-driven battle. Experts play cards for battle back, exploit terrain for defense, and target weakened flanks.", quickTips: ["Battle back: defender attacks if they survive.", "Terrain: hills reduce damage.", "Play card matching section with most units.", "Weakened flank: attack where opponent has fewest blocks."], strategy: ["Battle back exploitation: leave 1 block to survive and battle back—2 damage for 1 block trade.", "Terrain lines: hills and towns give defense; hold terrain with few blocks.", "Card-section matching: play left card when left flank has 4+ units—maximizes activation.", "Weakened flank: attack flank with 2 blocks; don't attack 4-block center.", "Leadership: leadership card adds to all battles that turn—play when 2+ battles.", "Endgame: when opponent has 2 flags, attack aggressively—flags win, not block preservation."] },
    { metaDescription: "Uzman Commands & Colors: geri vurus ve zayif kanat.", intro: "Commands & Colors kart suruculu savastir.", quickTips: ["Savunan hayatta kalirsa vurur.", "Tepe hasar azaltir.", "En cok birimli bolume kart.", "En zayif kanada saldir."], strategy: ["1 blok ile geri vurus.", "Arazi az blokla tutulur.", "4+ birimli kanada kart.", "2 bloklu kanada saldiri.", "Liderlik 2+ savasta.", "2 bayrakta agresif."] },
    { metaDescription: "Commands-Colors-Expertenstrategie: Battle-Back.", intro: "Commands & Colors ist kartengetriebene Schlacht.", quickTips: ["Battle Back wenn ueberlebt.", "Huegel reduziert Damage.", "Karte zur groessten Sektion.", "Schwache Flanke angreifen."], strategy: ["1 Block fuer Battle Back.", "Terrain mit wenig Blocks.", "Left Card bei 4+ Units.", "2-Block-Flanke angreifen.", "Leadership bei 2+ Battles.", "2 Flags = aggressiv."] }
  ),

  sekigahara: g("strategy-war-games", "complicated",
    { metaDescription: "Expert Sekigahara: loyalty testing, battle card commitment, and deployment zone control.", intro: "Sekigahara is loyalty testing and battle commitment. Experts test opponent loyalty with small battles and commit cards when loyalty is confirmed.", quickTips: ["Loyalty: opponent may betray if you attack their daimyo.", "Test loyalty with small battles first.", "Commit elite cards when loyalty confirmed.", "Deployment: control central deployment zones."], strategy: ["Loyalty testing: attack with 1-2 units first; if opponent commits, loyalty likely true.", "Battle card commitment: save elite cards for decisive battle; don't commit on loyalty tests.", "Deployment zone control: central zones give reinforcement advantage; control before main battle.", "Betrayal timing: betray when opponent has committed elite cards—wipe their army.", "Daimyo protection: keep daimyo behind front line; daimyo loss = army collapse.", "Endgame: when 2 armies remain, loyalty test all opponents before final battle."] },
    { metaDescription: "Uzman Sekigahara: sadakat testi ve savas karti bagliligi.", intro: "Sekigahara sadakat testi ve savas bagliligidir.", quickTips: ["Daimyo saldirisi ihanet riski.", "Kucuk savasla sadakat test et.", "Sadakat onayinda elit kart.", "Merkez bolge kontrolu."], strategy: ["1-2 birimle test.", "Elit karti belirleyici savasta.", "Merkez bolge takviye.", "Elit commit sonrasi ihanet.", "Daimyo arka planda.", "2 ordu kalinca test."] },
    { metaDescription: "Sekigahara-Expertenstrategie: Loyalty-Testing.", intro: "Sekigahara ist Loyalty-Testing und Battle-Commitment.", quickTips: ["Daimyo-Attack = Betrayal-Risk.", "Kleine Battles zum Test.", "Elite bei bestaetigter Loyalty.", "Zentrale Deployment-Zones."], strategy: ["1-2 Units Test.", "Elite bei decisive Battle.", "Central Zone Control.", "Betray nach Elite-Commit.", "Daimyo hinter Front.", "Loyalty-Test vor Final."] }
  ),

  "pax-pamir": g("strategy-war-games", "complicated",
    { metaDescription: "Expert Pax Pamir: coalition pivoting, spy network placement, and dominance vs victory condition racing.", intro: "Pax Pamir is coalition pivoting in the Great Game. Experts pivot between British and Russian coalitions, place spies for network control, and race dominance vs victory conditions.", quickTips: ["Coalition: pivot when your coalition is winning.", "Spies: place in contested territories.", "Dominance: 4+ points in one coalition.", "Victory: complete patron agenda."], strategy: ["Coalition pivoting: join winning coalition by turn 3; pivot to losing coalition if they offer better patron cards.", "Spy network: spies in 3+ territories give card draw; place in territories opponents need.", "Dominance path: 4+ coalition points wins; military cards give coalition points.", "Victory path: patron agenda (e.g., 3 military victories) wins; agenda cards guide deck.", "Tableau building: buy cards matching patron; don't diversify.", "Endgame: when opponent has 3 coalition points, pivot or block their 4th."] },
    { metaDescription: "Uzman Pax Pamir: koalisyon pivotu ve casus agi.", intro: "Pax Pamir Buyuk Oyunda koalisyon pivotudur.", quickTips: ["Kazanan koalisyona gec.", "Casuslari tartisilan bolgelere.", "4+ puan baskinlik.", "Patron gundemi zafer."], strategy: ["3. tura kadar kazanan taraf.", "3+ bolgede casus.", "Askeri kart koalisyon puanı.", "Patron gundemine uygun deste.", "Rakip 3 puanda blok."] },
    { metaDescription: "Pax-Pamir-Expertenstrategie: Coalition-Pivoting.", intro: "Pax Pamir ist Coalition-Pivoting im Great Game.", quickTips: ["Zur winning Coalition.", "Spies in contested Territories.", "4+ Points Dominance.", "Patron Agenda Victory."], strategy: ["Winning Coalition bis R3.", "Spies in 3+ Territories.", "Military = Coalition Points.", "Deck nach Patron.", "Block bei 3 Points."] }
  ),

  "coin-series": g("strategy-war-games", "complicated",
    { metaDescription: "Expert COIN series: faction eligibility, operation sequencing, and event card leverage for multi-faction tempo.", intro: "COIN series games are asymmetric insurgency. Experts maximize faction eligibility, sequence operations for compound effects, and leverage events for tempo.", quickTips: ["Eligibility: pass when you can't act effectively.", "Operations: pair with capability for bonus.", "Events: play when opponent faction benefits less.", "Train/assault: clear enemies before building."], strategy: ["Faction eligibility: pass if no good operation—forcing others to act first gives information.", "Operation sequencing: Propaganda then Build then Attack—each compounds.", "Event leverage: play event when your faction gains more than opponent's eligible faction.", "Train before assault: train troops increase assault success; assault without train wastes.", "Control vs opposition: COIN factions need 2+ more control than opposition; focus control in key spaces.", "Multi-faction: in 4-faction games, negotiate to eliminate leader—3-way beats 1 leader."] },
    { metaDescription: "Uzman COIN serisi: uygunluk ve operasyon sirasi.", intro: "COIN serisi asimetrik ayaklanmadir.", quickTips: ["Etkisizse pas gec.", "Operasyon+yetenek bonusu.", "Rakip daha az fayda gorurse olay oyna.", "Insa oncesi temizlik."], strategy: ["Bilgi icin pas.", "Propaganda>insa>saldiri.", "Kendi lehine olay.", "Egitim sonra saldiri.", "Anahtar bolgelerde kontrol.", "Lideri elemek icin muzakere."] },
    { metaDescription: "COIN-Series-Expertenstrategie: Eligibility und Operations.", intro: "COIN-Serie ist asymmetrische Insurgency.", quickTips: ["Passen wenn ineffektiv.", "Operation+Capability Bonus.", "Event wenn Gegner weniger profitiert.", "Train vor Assault."], strategy: ["Pass fuer Information.", "Propaganda>Build>Attack.", "Event bei eigenem Vorteil.", "Train vor Assault.", "Control in Key Spaces.", "Leader eliminieren verhandeln."] }
  )
};
